### ISSUE TITLE
Inlining the partial functions

### ISSUE THREAD

**Issue by KristofferC** [JuliaDiff/ForwardDiff.jl#108]
It could be worth looking into adding a ` $(Expr(:meta, :inline))` to the generated functions used for the partials.

I have some code that uses a type with a `NTuple` and inlining these operations sometimes give a significant boost.

**Comment by KristofferC** [comment]
I don't see that much of a boost running it with ForwardDiff but I will leave this open so we can investigate when everything is in place for some real benchmarking.

**Comment by jrevels** [comment]
Accomplished in #102.
