### ISSUE TITLE
Forward AD for mod2pi()

### ISSUE THREAD

**Issue by papamarkou** [JuliaDiff/ForwardDiff.jl#113]
Hi @jrevels, @mlubin, how easy would it be to implement forward AD for  the `mod2pi()` function? @eford, a collaborator, would like to make use of such functionality. Would it be possible to help with this? If you are too busy to help with it, then perhaps even some guidelines would be valuable.

**Comment by jrevels** [comment]
I think we also just need general `mod` as well. That was implemented in `DualNumbers` a while ago (ref JuliaDiff/DualNumbers.jl#25).

**Comment by scidom** [comment]
Thanks, @jrevels. I was reading the ForwardDiff documentation, according to which we would first need to open a PR in Calculus. I was wondering whether the Calculus prerequisite is covered for `mod` or its implementation in DualNumbers was independent, not implicating Calculus.

**Comment by devmotion** [comment]
A rule for `mod2pi` was added to DiffRules, and hence also automatically to ForwardDiff, a while ago (https://github.com/JuliaDiff/DiffRules.jl/pull/35):
```julia
julia> using ForwardDiff

julia> ForwardDiff.derivative(mod2pi, 1.0)
1.0
```

**Comment by eford** [comment]
Thanks
