### ISSUE TITLE
Restrict Domain on ForwardDiff inputs

### ISSUE THREAD

**Issue by rand5** [JuliaDiff/ForwardDiff.jl#114]
Hi,

I keep running up against a scenario where ForwardDiff returns an array of NaNs for the Hessian of my input function. I have tracked the issue down to a single line of code and have put together the following example of the problem:

```
function foo(α::Vector)
    dM = 10.;
    Ve = collect(0.:dM)
    γ = Ve.^α[1];
    γ = sum(γ)
    return γ
end
```

```
hess, allresults = ForwardDiff.hessian(foo, rand(1), ForwardDiff.AllResults)

 (
1x1 Array{Float64,2}:
 NaN,

ForwardDiff.ForwardDiffResult{ForwardDiff.HessianNumber{1,Float64,Tuple{Float64}}}(ForwardDiff.HessianNumber{1,Float64,Tuple{Float64}}(ForwardDiff.GradientNumber{1,Float64,Tuple{Float64}}(15.451578575296926,ForwardDiff.Partials{Float64,Tuple{Float64}}((NaN,))),[NaN])))
```

My original function is restricted to α on the open interval (0,2). The issue appears to be that ForwarDiff keeps trying to evaluate 0^α for α<0, since if I replace `Ve = collect(0.:dM)` with `Ve = collect(c:dM)` where 0<c<dM, the hessian no longer contains NaNs. Since I need the first element of Ve to be zero I am interested to know if there is a way to restrict ForwardDiff's choice of perturbations of the input variable to a specific domain. I checked the ForwardDiff documentation, but didn't come across anything that proved helpful.

Thanks in advance!

**Comment by mlubin** [comment]
ForwardDiff only evaluates at the exact point which you give it, so it's not evaluating it for α<0. We may need to add a special case for powers where the base is zero.

**Comment by rand5** [comment]
Ok, that explains why it was returning NaNs and not Infs..

**Comment by jrevels** [comment]
You can differentiate w.r.t. intervals of values if you use the `Interval` type from the [ValidatedNumerics.jl](https://github.com/dpsanders/ValidatedNumerics.jl) package, but I'm not sure that will give you what you're looking for here. 

Closing this since ForwardDiff [is actually giving the correct answer](https://github.com/JuliaDiff/ForwardDiff.jl/issues/118#issuecomment-263073926).
