### ISSUE TITLE
strange Cholesky decomposition problem

### ISSUE THREAD

**Issue by wilbur-t** [JuliaDiff/ForwardDiff.jl#118]
Hello again! Sorry to spam with issues, hopefully you find them useful.

I've been using ForwardDiff to differentiate a function that includes a Cholesky decomposition. (To simulate a likelihood function, in case you were wondering.) I never bothered to learn the Cholesky decomposition algorithm so was pretty stoked/surprised that this seemed to work well. Unfortunately I changed the underlying covariance matrix and am now getting errors.

This code replicates my problem:

```
julia> using ForwardDiff 

julia> # L is the Cholesky decomposition of the covariance matrix 
julia> cov(d, rho) = d * ones(2,2) + rho.^[0. 1.; 1. 0.] 
cov (generic function with 1 method) 
julia> L(d, rho) = chol(cov(d, rho)) 
L (generic function with 1 method) 

julia> L(1., 0.) 
2x2 UpperTriangular{Float64,Array{Float64,2}}: 
1.41421 0.707107 
0.0 1.22474 
julia> ForwardDiff.derivative(th -> sum(L(th, 0.)), 1.)
0.9859455490991501
julia> ForwardDiff.derivative(th -> sum(L(1., th)), 0.)
ERROR: ArgumentError: x must be positive semidefinite in chol! at linalg/cholesky.jl:92
in chol! at linalg/cholesky.jl:43
in chol at linalg/cholesky.jl:83
in L at none:1
in anonymous at none:1
in derivative at H:\.julia\v0.4\ForwardDiff\src\api\derivative.jl:24
```

Note that the covariance matrix is positive definite at (1, 0), and can be differentiated in its first parameter. However when I try to differentiate it in its second parameter at, I'm told that the matrix isn't positive definite.

If the matrix `rho.^[0. 1.; 1. 0.]` is defined explicitly as in `cov(d, rho) = d * ones(2,2) + [1. rho; rho 1]`, the function `L` can be differentiated in both parameters without any problems. (Though given my actual application includes a 9x9 matrix covariance matrix, that solution is sub-optimal.)

**Comment by jrevels** [comment]
This is probably #96 combined with the inequality test [here](https://github.com/JuliaLang/julia/blob/master/base/linalg/cholesky.jl#L93).

**Comment by jrevels** [comment]
After #102, this now returns a `NaN` instead of an error:

```julia
julia> ForwardDiff.derivative(th -> sum(L(1., th)), 0.)
NaN
```

**Comment by jrevels** [comment]
This `NaN` is essentially coming from the fact that you end up taking the partial derivative of `rho^0.0` w.r.t. to `rho` where `rho = 0`. Using `Dual` numbers:

```julia
julia> ForwardDiff.Dual(0.0, 1.0)^0.0
Dual(1.0,NaN)
```

...which [is correct](https://www.wolframalpha.com/input/?i=derivative+of+x%5Ey+w.r.t+x+for+x+%3D+0,+y+%3D+0) (it's equivalent to `0.0 * 0.0^-1.0`). As you found, rewriting that part of your objective function as `[1. rho; rho 1]` sidesteps this mathematical quirk.
