### ISSUE TITLE
gradient fails with type errors

### ISSUE THREAD

**Issue by RossBoylan** [JuliaDiff/ForwardDiff.jl#123]
I think I'm following the example in the documentation, but am unable to get an actual answer.
```
julia> f(x::Vector{Float64}) = RB.logitlite(RB.obs, x, 7)
 f (generic function with 1 method)

 julia> g = ForwardDiff.gradient(f)
 g (generic function with 1 method)

 julia> @time g1 = g(RB.troubleParamsSim1.raw)
 ERROR: MethodError: `f` has no method matching f(::Array{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Flo\
 at64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},1})
  in _calc_gradient at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
  in g at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54

  julia> typeof(RB.troubleParamsSim1.raw)
 Array{Float64,1}
 
 julia> methods(f)
 # 1 method for generic function "f":
 f(x::Array{Float64,1}) at none:1

 julia> f(x::Vector) = RB.logitlite(RB.obs, x, 7)
 f (generic function with 2 methods)

 julia> g = ForwardDiff.gradient(f);

 julia> @time g1 = g(RB.troubleParamsSim1.raw)
 ERROR: MethodError: `logitlite` has no method matching logitlite(::DataFrames.DataFrame, ::Array{ForwardDiff.Gra\
 dientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},1\
 }, ::Int64)
 Closest candidates are:
   logitlite(::DataFrames.AbstractDataFrame, !Matched::RB.Coefficients{Float64}, ::Int64)
   logitlite(::DataFrames.AbstractDataFrame, !Matched::Array{Float64,1}, ::Int64)
  in f at none:1
  in _calc_gradient at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
  in g at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54

 julia> f(x::Vector) = RB.logitlite(RB.obs, Vector{Float64}(x), 7)
 f (generic function with 2 methods)

 julia> g = ForwardDiff.gradient(f);

!julia> @time g1 = g(RB.troubleParamsSim1.raw)
 ERROR: InexactError()
  in setindex! at array.jl:313
  in copy! at abstractarray.jl:310
  in f at none:1
  in _calc_gradient at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
  in g at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54
 
```

The relevant signature for logitlite is `function logitlite(data::AbstractDataFrame, params::Vector{Float64}, npoints::Int64)`

Is the fact that logitlite is defined in a module causing trouble?

There were initially problems using the  package; however I restarted the session since then and got no load errors this time--although there were a lot of packages recompiled.  The current session did not recompile Calculus or ForwardDiff.

Here are the earlier difficulties:
```
julia> Pkg.add("ForwardDiff")
 INFO: Cloning cache of ForwardDiff from git://github.com/JuliaDiff/ForwardDiff.jl.git
 INFO: Installing ForwardDiff v0.1.8
 INFO: Package database updated

 julia> f(x::Vector{Float64}) = RB.logitlite(RB.obs, x, 7)
 f (generic function with 1 method)

 julia> using ForwardDiff
 INFO: Precompiling module ForwardDiff...
 INFO: Recompiling stale cache file /home/ross/.julia/lib/v0.4/Compat.ji for module Compat.
 INFO: Recompiling stale cache file /home/ross/.julia/lib/v0.4/Calculus.ji for module Calculus.
 INFO: Recompiling stale cache file /home/ross/.julia/lib/v0.4/ForwardDiff.ji for module ForwardDiff.
 WARNING: Module Calculus uuid did not match cache file
   This is likely because module Calculus does not support  precompilation but is imported by a module that does.
 ERROR: __precompile__(true) but require failed to create a precompiled cache file
  in require at ./loading.jl:268

 julia> using Calculus

 julia> using ForwardDiff
 INFO: Recompiling stale cache file /home/ross/.julia/lib/v0.4/ForwardDiff.ji for module ForwardDiff.
 WARNING: Module Calculus uuid did not match cache file
   This is likely because module Calculus does not support  precompilation but is imported by a module that does.
 WARNING: deserialization checks failed while attempting to load cache from /home/ross/.julia/lib/v0.4/ForwardDif\
 f.ji
 INFO: Precompiling module ForwardDiff...
 INFO: Recompiling stale cache file /home/ross/.julia/lib/v0.4/ForwardDiff.ji for module ForwardDiff.
 WARNING: Module Calculus uuid did not match cache file
   This is likely because module Calculus does not support  precompilation but is imported by a module that does.
 ERROR: __precompile__(true) but require failed to create a precompiled cache file
  in require at ./loading.jl:268

Running on
   | | |_| | | | (_| |  |  Version 0.4.6-pre+28 (2016-04-22 00:59 UTC)
  _/ |\__'_|_|_|\__'_|  |  Commit 022917e (24 days old release-0.4)
 |__/                   |  x86_64-linux-gnu
```

**Comment by gragusa** [comment]
The arguments of your functions are defined to tightly. As you can see from
the error, the function does not have a method for GradientNumber. Try
define f more generally.

**Comment by RossBoylan** [comment]
My 2nd try was `f(x::Vector) = RB.logitlite(RB.obs, x, 7)`  (see original transcript) which solved the initial problem.  But it pushed it down another level, since the function f called got called with `::Array{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}}`
I can loosen the requirement for that function, but I don't know what that type is and I'm beginning to suspect this will push the type problem further down.
Is there a reqirement that the calculations being done must be loosely enough typed that these ForwardDiff types can be used for all calculations?

**Comment by mlubin** [comment]
> Is there a reqirement that the calculations being done must be loosely enough typed that these ForwardDiff types can be used for all calculations?

[Yes](http://www.juliadiff.org/ForwardDiff.jl/perf_diff.html#restrictions-on-the-target-function)

**Comment by RossBoylan** [comment]
I've tried relaxing the types, but still get 
`
julia> using ForwardDiff
julia> g=ForwardDiff.gradient(RB.mylike)
 g (generic function with 1 method)

!julia> @time g(RB.troubleParamsInit.raw)
 ERROR: MethodError: `convert` has no method matching convert(::Type{RB.Coefficients{T}}, ::Array{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},1})
 This may have arisen from a call to the constructor RB.Coefficients{T}(...),
 since type constructors fall back to convert methods.
 Closest candidates are:
   call{T}(::Type{T}, ::Any)
   convert{T}(::Type{T}, !Matched::T)
  in logitlite at /home/ross/PCORI/trouble.jl:316
  in mylike at /home/ross/PCORI/trouble.jl:345
  in _calc_gradient at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
  in g at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54
`

Some context:
`
mylike(v) = -logitlite(RB.obs, v, 7)

function logitlite(data::AbstractDataFrame, params, npoints::Int64)
    c = Coefficients(params)
    logitlite(data, c, npoints)
end

function logitlite(data::AbstractDataFrame, c::Coefficients, npoints::Int64)
....# included nested function definitions
end

type Coefficients{T}
    raw::Vector{T}
    σ_0::T
    σ_T::T
    ρ::T
    ν::T
    Σ::Matrix{T}
    # because of this c'tor the type must be mutable  
    function Coefficients{T}(vals::Vector{T})
        if length(vals) ≠ 10
            error("Must have exactly 10 parameters")
        end
        self = new(vals)
        self.σ_0 = exp(lnσ_0(self))
        self.σ_T = exp(lnσ_T(self))
        self.ρ = tanh(atanhρ(self))
        self.ν = exp(lnν(self))
        # chol doesn't work on SymTridiagonal  
        self.Σ = Matrix(SymTridiagonal([ self.σ_0, self.σ_T].^2, [self.ρ * self.σ_0 * self.σ_T]))
        self
    end
end

`

So for the derivatives to be effective they need to flow through the derived values in  Coefficients.
I thought loosening the type on Coefficients would permit the differentiable value to flow through it.  It's not clear to me why it isn't working, since I think `::Array{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},1}` is `Vector{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}}}`

**Comment by RossBoylan** [comment]
Solved the  problem above, but the next  problem appears to involve code in the Distributions package:
`julia> g=ForwardDiff.gradient(RB.mylike)
 g (generic function with 1 method)

!julia> @time g(RB.troubleParamsInit.raw)
 ERROR: MethodError: `convert` has no method matching convert(::Type{Distributions.MvNormal{Cov<:PDMats.AbstractPDMat{T\
 <:Real},Mean<:Union{Array{Float64,1},Distributions.ZeroVector{Float64}}}}, ::Array{ForwardDiff.GradientNumber{10,Float64,Tuple{Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64,Float64}},2})
 This may have arisen from a call to the constructor Distributions.MvNormal{Cov<:PDMats.AbstractPDMat{T<:Real},Mean<:Un\
 ion{Array{Float64,1},Distributions.ZeroVector{Float64}}}(...),
 since type constructors fall back to convert methods.
 Closest candidates are:
   call{T}(::Type{T}, ::Any)
   convert{T}(::Type{T}, !Matched::T)
   Distributions.MvNormal(!Matched::Array{Float64,1})
   ...
  in makeQuad at /home/ross/PCORI/trouble.jl:66
  in logitlite at /home/ross/PCORI/trouble.jl:265
  in logitlite at /home/ross/PCORI/trouble.jl:319
  in mylike at /home/ross/PCORI/trouble.jl:347
  in _calc_gradient at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
  in g at /home/ross/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54
`
It looks as if Distributions.MvNormal requires Array{Float64,1}, which is incompatible with the ForwardDiff types.

**Comment by jrevels** [comment]
This is an issue for the Distributions package, see JuliaStats/Distributions.jl#423
