### ISSUE TITLE
Possible bug in simple function that uses for loop?

### ISSUE THREAD

**Issue by ngiann** [JuliaDiff/ForwardDiff.jl#132]
Sorry for the vague title, but the example that troubles me is so simple that I didn't know how to name it any better. In short: I have coded a simple function in two different ways and both versions should (and do) return the same result. However, they behave differently if I try to get the gradient automatically.
Specifically, here follow the two versions of the function:

```
#######################################################
function version_one(mu,X)
#######################################################

  aux = 0.0
  for nn=1:size(X,2)
    aux +=  sum( (X[:,nn]-mu).^2)
  end

  return aux

end

#######################################################
function version_two(mu,X)
#######################################################

  N = size(X,2)
  aux = zeros(N)
  for nn=1:N
    aux[nn] = sum( (X[:,nn]-mu).^2)
  end
  return sum(aux)

end
```

Let us test the functions:

```
X = randn(2,3) # some random data
mu = [1.0;2.0] # arbitrary mean
@show version_one(mu,X) # works fine for me
@show version_two(mu,X) # works fine for me
```

Let us try to get the gradients:
```
ForwardDiff.gradient( ARG -> version_one(ARG,X), mu)
ForwardDiff.gradient( ARG -> version_two(ARG,X), mu)
```

The first call to ForwardDiff.gradient works fine, the second fails and gives me:

> ERROR: MethodError: `convert` has no method matching convert(::Type{Float64}, ::ForwardDiff.Dual{2,Float64})
> This may have arisen from a call to the constructor Float64(...),
> since type constructors fall back to convert methods.
> Closest candidates are:
>   call{T<:AbstractFloat}(::Type{T<:AbstractFloat}, ::Real, ::RoundingMode{T})
>   call{T}(::Type{T}, ::Any)
>   convert(::Type{Float64}, ::Int8)
>   ...
>  in version_two at none:8
>  in anonymous at none:1

I could be doing something wrong, but it is so elementary that I do not see what could possibly be wrong. I am using Julia Version 0.4.6.

**Comment by gragusa** [comment]
Change the call to zeros as zeros(eltype(mu)).

**Comment by ngiann** [comment]
Careless mistake on my side, thanks very much,
