### ISSUE TITLE
Julia quits when multiplying sparse matrices

### ISSUE THREAD

**Issue by matthieugomez** [JuliaDiff/ForwardDiff.jl#133]
```julia
Pkg.status("ForwardDiff")
# - ForwardDiff                   0.2.1
using ForwardDiff
A = zeros(ForwardDiff.Dual{10,Float64}, 2, 2)
b = zeros(ForwardDiff.Dual{10,Float64}, 2)
A * b
#2-element Array{ForwardDiff.Dual{10,Float64},1}:
# Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
# Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
sparse(A) * b
#Assertion failed: (MRI->getVRegDef(reg) && "Register use before def!"), function #HandleVirtRegUse, file LiveVariables.cpp, line 133.
#signal (6): Abort trap: 6
#__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
#[1]    55640 abort      julia
#julia  11.84s user 10.02s system 16% cpu 2:08.62 total
```

**Comment by mlubin** [comment]
``versioninfo()``? I can't reproduce this on 0.4 or 0.5.

**Comment by matthieugomez** [comment]
```
versioninfo()
Julia Version 0.4.5
Commit 2ac304d* (2016-03-18 00:58 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.4.0)
  CPU: Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by KristofferC** [comment]
fwiw works on 0.5 for me

**Comment by matthieugomez** [comment]
If that helps,  `ForwardDiff.Dual{i,Float64}` works well up to 9.

**Comment by jrevels** [comment]
Hmm, I also can't reproduce this on v0.4 or v0.5. Here's my output (it's basically the same for both v0.4 and v0.5):

```julia
julia> using ForwardDiff

julia> A = zeros(ForwardDiff.Dual{10,Float64}, 2, 2)
2x2 Array{ForwardDiff.Dual{10,Float64},2}:
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)  Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)  Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

julia> b = zeros(ForwardDiff.Dual{10,Float64}, 2)
2-element Array{ForwardDiff.Dual{10,Float64},1}:
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

julia> A * b
2-element Array{ForwardDiff.Dual{10,Float64},1}:
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)

julia> sparse(A) * b
2-element Array{ForwardDiff.Dual{10,Float64},1}:
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
 Dual(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0)
```

The only discrepancy I can see here is the output you posted for `A * b` doesn't have the right number of epsilon components for the type `Dual{10}`; maybe that was just a copy-paste mishap?

**Comment by matthieugomez** [comment]
Yes it's a typo I corrected it.

**Comment by matthieugomez** [comment]
I have the same bug when deriving a function that does not use sparse matrices. Any idea where this comes from? It's super hard to pinpoint the problem since julia just quits : if I add some `@show "ok until here"' they don't print even if they are before the problematic line.

**Comment by KristofferC** [comment]
Someone else has some problems with fdiff and matrices but not sure it is related. Posting it here just in case. https://github.com/EconForge/NLsolve.jl/issues/59

**Comment by jrevels** [comment]
> I have the same bug when deriving a function that does not use sparse matrices

We couldn't reproduce your original problem, but if you post a different function I can try that out as well. 

From your `versioninfo` above, it seems like you're not using a standard release version of Julia (I'm assuming that's what the star after the commit means)? Do you get the same bug on an official Julia release?

**Comment by matthieugomez** [comment]
The issue is that the function is very complicated. I'm trying to understand which line creates the issue by some `show` macro, but, as said in the previous post, they never print anyway. So I'm having some hard time to give you a simple example.

**Comment by maleadt** [comment]
Could not reproduce either, tried on julia at 2ac304d + sandybridge CPU, only difference being the OS.
Just to confirm, you're running into this issue with an otherwise unmodified build of Julia at commit 2ac304d (also meaning no `Make.user`), with a vanilla ForwardDiff at v0.2.1, running only the code from your post in a REPL (also meaning `--no-startup`)?

If so, could you make a debug build of Julia (0.5, if it reproduces the issue) as follows: `make debug LLVM_ASSERTIONS=1 LLVM_DEBUG=1`, and run your repro as follows: `JULIA_LLVM_ARGS="-debug -print-before-all" /path/to/julia-debug --startup-file=no repro.jl 2>&1 1>debug.log` (first run it once without the environment flags to verify the issue and trigger recompilation).
Beware that this will generate a _huge_ file, easily exceeding 1GB (so better compress it afterwards).

**Comment by matthieugomez** [comment]
I don't have the issue with julia 0.5. I'm going to close the issue since I was the only one with it to begin with.
