### ISSUE TITLE
Broken docs page

### ISSUE THREAD

**Issue by jrevels** [JuliaDiff/ForwardDiff.jl#140]
[Our docs site](http://www.juliadiff.org/ForwardDiff.jl/) broke after switching to GitHub's new [hosting-from-`master` option](https://github.com/blog/2228-simpler-github-pages-publishing) - it's now 404ing when it tries to load the JS included in the `_static` folder. I can't reproduce it locally, unfortunately, so there's something GitHub-Pages-specific going on. 

This problem isn't necessarily due to the new hosting option, because switching back to the old `gh-pages` option didn't fix it. I think GitHub must've altered something on their end since the last time our docs were updated.

Anybody savvy with GitHub Pages stuff?

**Comment by mlubin** [comment]
I've found github support to be generally responsive for things like this.

**Comment by jrevels** [comment]
Welp, it seems that I just didn't wait long enough. As I was writing up a support email, the docs site fixed itself.
