### ISSUE TITLE
isapprox() for Duals

### ISSUE THREAD

**Issue by dbeach24** [JuliaDiff/ForwardDiff.jl#151]
`isapprox()` only operates on the `Dual.value`.  This result was a little surprising to me at first.

```jl
julia> x = Dual(1.0, 2.0, 3.0)
Dual(1.0,2.0,3.0)

julia> y = Dual(1.0, 2.0, 4.0)
Dual(1.0,2.0,4.0)

julia> isapprox(x, y)
true
```

I think I understand why Duals need to be treated as though only their `value` component matters when doing comparisons.  This rule is necessary for using `Duals` in code that is written generically for other `real` values.  Should this rule extend to `isapprox()`?  Or should there be some other function for value-checking Dual numbers, including all of their partials?

**Comment by mlubin** [comment]
The convention so far is that whenever there's a conflict between the AD interpretation and the mathematical interpretation is to favor the AD interpretation. You could easily have user code that takes a different path depending on the value of ``isapprox``, so if we return a different answer than if you only looked at the real parts, AD on this code will be broken.

**Comment by dbeach24** [comment]
Seems very reasonable.  Would it make sense to have some other function (similar to `isapprox`) which compares both primary and partial values?

**Comment by jrevels** [comment]
It's easy enough for users to define their own such function, so it's probably not warranted for us to provide it (especially since it'd only be an internal function anyway). [Note that we already have something similar for our own tests](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/test/DualTest.jl#L309).

**Comment by dbeach24** [comment]
Thanks.  Fair enough.
