### ISSUE TITLE
gradient() now works properly with StaticArrays

### ISSUE THREAD

**Issue by rdeits** [JuliaDiff/ForwardDiff.jl#159]
This is not a bug, but rather an improvement that you might not have been aware of. It looks like d9809c6543db95ab384b24701a3a17226660b603 had a side-benefit of fixing an issue I have been running into, in which StaticArrays MVector types caused errors when taking gradients:

before:

```julia
julia> ForwardDiff.gradient(x -> sum(x), MVector(1., 2., 3.))
ERROR: TypeError: typeassert: expected Tuple{ForwardDiff.JacobianCache{3,Float64,StaticArrays.MVector{3,ForwardDiff.Dual{3,Float64}}}}, got Tuple{ForwardDiff.JacobianCache{3,Float64,Array{ForwardDiff.Dual{3,Float64},1}}}
 in multithread_jacobian_cachefetch!(::StaticArrays.MVector{3,Float64}, ::ForwardDiff.Chunk{3}, ::Bool, ::Bool) at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/cache.jl:71
 in jacobian_cachefetch! at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/cache.jl:74 [inlined]
 in compute_vector_mode_gradient(::##5#6, ::StaticArrays.MVector{3,Float64}, ::ForwardDiff.Chunk{3}, ::Bool) at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/gradient.jl:87
 in vector_mode_gradient at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/gradient.jl:94 [inlined]
 in #gradient#33(::Bool, ::Bool, ::Function, ::Function, ::StaticArrays.MVector{3,Float64}, ::ForwardDiff.Chunk{3}) at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/gradient.jl:23
 in gradient(::Function, ::StaticArrays.MVector{3,Float64}, ::ForwardDiff.Chunk{3}) at /Users/rdeits/locomotion/explorations/point-cloud-signed-distance/packages/v0.5/ForwardDiff/src/gradient.jl:22 (repeats 2 times)
```

and after d9809c6543db95ab384b24701a3a17226660b603 :

```julia
julia> ForwardDiff.gradient(x -> sum(x), MVector(1., 2., 3.))
3-element StaticArrays.MVector{3,Float64}:
 1.0
 1.0
 1.0
```

Thanks for all your hard work! ForwardDiff is awesome!

**Comment by jrevels** [comment]
Oh, awesome, thanks for letting us know and for the kind words!

Note that this will probably only work when the chunk size equals the input dimension, and the max chunk size right now is (somewhat arbitrarily) capped at `10`. I suppose this is a point in favor for moving back to using `@generated` functions in the `Partials` code...

**Comment by rdeits** [comment]
Actually, it seems to work fine for arbitrary-sized MVector inputs (at least up to 100). I think it's independent of the chunk size, since what actually gets passed into the function is an `MVector{InputSize, Dual{ChunkSize, Float64}}`. For example:

```julia
julia> ForwardDiff.gradient(x -> (@show typeof(x); sum(x)), zeros(MVector{15, Float64}))
typeof(x) = StaticArrays.MVector{15,ForwardDiff.Dual{8,Float64}}
typeof(x) = StaticArrays.MVector{15,ForwardDiff.Dual{8,Float64}}
```

In any case, closing this, since it's not actually an issue 😄

**Comment by jrevels** [comment]
Oh, cool! I had assumed it wouldn't work because calculations where `chunk size != input length` require a mutable array, but didn't realize (until I checked just now) that StaticArrays implemented mutable array types. 

Thanks again for the heads up!
