### ISSUE TITLE
Unexpected promotion of dual numbers with sqrt

### ISSUE THREAD

**Issue by KristofferC** [JuliaDiff/ForwardDiff.jl#169]
```jl
julia> a = ForwardDiff.Dual(Float32(1), Float32(2))
Dual(1.0,2.0)

julia> typeof(a)
ForwardDiff.Dual{1,Float32}

julia> typeof(sqrt(a))
ForwardDiff.Dual{1,Float64}
```

The issue is the multiplication with 0.5 here: https://github.com/JuliaDiff/ForwardDiff.jl/blob/b467b89cbc2119d449a1bf14c106d94280f2f548/src/dual.jl#L342

Could either change it to `  / 2` but that might be a performance hit. Could also promote the `0.5` to the number type of the input argument but that might not be possible for some input types. Could also just convert the result to the same number type as the valtype of the input dual number.

**Comment by jrevels** [comment]
Nice catch. Changing `0.5` to `0.5f0` works for the `Float32` case, maybe in general it should be `promote_type(T, Float16)(0.5)`? I'll look into it.
