### ISSUE TITLE
Autodifferentiation to return a function, or simulate with caching?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/ForwardDiff.jl#180]
For many differential equations problems, I need to autodifferentiate a function `f(t,u)`, in both `t` and `u`. But every step of the iteration, I need both derivatives. So what I have been doing is the following:

```julia
        ForwardDiff.derivative!(dT,(t)->vecfreturn(t,u,du2),t) # Time derivative
        ForwardDiff.jacobian!(J,(du1,u)->vecf(t,u,du1),vec(du1),vec(u))
```

(note: the extra details is that `f` is actually in-place and writes to `du1`/`du2` which is a cache, this was from https://github.com/JuliaDiff/ForwardDiff.jl/issues/136 but can be ignored).

However, I was wondering if there was a way to not have to generate those closures every timestep. Is there a way to autodifferentiate and get a function out? Like get a function of `u` out for `df/dt`? Or is that not possible with operator overloading at all?

One way I am looking into implementing this is via call overloading. What I can do is this:

```julia
type TimeDerivativeFunction{T,T2}
  u::T
  cache::T2
end
(p::TimeDerivativeFunction)(t) = vecfreturn(t,p.u,p.cache)
ft = TimeDerivativeFunction(u,du2)
```

and then use it like:

```julia
# ft.u = u # If this pointer gets set once, it actually doesn't need to update
ForwardDiff.derivative!(dT,ft,t)
```

My question with this is, will ForwardDiff.jl be caching correctly to handle this case? In many cases, `f(t,u,du)` is actually not dependent on `t`, so will it be able to cache that the derivative is independent of `u` and thus automatically speed it up like it would if it calculated some explicit function `dfdt(u)`?

I hope this all makes sense.

**Comment by KristofferC** [comment]
What ForwardDiff does is conceptually not complicated. It takes your (real) input vector, creates a new vector consisting of dual numbers where the real part of the dual number is set to the input vector and the dual part is seeded in a specific way. It then calls the function. It then extracts the resulting dual part which will be the gradient / jacobian etc and returns it.

Now, I am a bit confused about what your question actually is. What do you mean with
>  will ForwardDiff.jl be caching correctly

Maybe you can have a small example with runnable code that can help pinpoint what the problem is?

**Comment by ChrisRackauckas** [comment]
```julia
f(t,u) = t+u
```

I want `dfdt(u)`, so the time derivative, but be able to keep changing `u`. Symbolic differentiation can make that exact function. I am wondering if it's possible for operator overloading automatic differentiation to make `dfdt(u)`, maybe using some unique type on `t`?

Or, the way to make this would be 

```julia
type TimeDerivativeFunction{T,T2}
  u::T
  cache::T2
end
(p::TimeDerivativeFunction)(t) = f(t,u)
ft = TimeDerivativeFunction(u)
```

and then use it like:

```julia
# ft.u = u # If this pointer gets set once, it actually doesn't need to update
ForwardDiff.derivative(ft,t) # derivative of f(t,u) by `t` at `u`
```

Would this end up being as efficient as an actually calculated `dfdt(u)`? I read that there's caching, so I am wondering if it somehow creates some psudo-`dfdt(t)` which is then re-evaluated at different `t`, and if I could just change `u` in it.

**Comment by KristofferC** [comment]
It will not be as efficient as `dfdt(u) = 1` 

The caching is just for work vectors that ForwardDiff need. These can be allocated beforehand so they can be used in multiple calls to i.e. `ForwardDiff.gradient`.

**Comment by ChrisRackauckas** [comment]
Okay, so then this is just a case where, since many related derivatives with a second variable changing need to be taken, symbolic differentiation will always have an advantage over automatic differentiation since it can directly compute the function? If that's the case, I'll just stick to the `TimeDerivativeFunction` trick and not try to push any further.

**Comment by KristofferC** [comment]
Which one is faster depends on the time it takes to evaluate your symbolic derivative vs. the time it takes to call your function with dual numbers.

**Comment by ChrisRackauckas** [comment]
I see. In this case, since the function calls can be very expensive and would have to be done every iteration (for many iterations), whereas the derivative can be calcuated once and heavily simplified as a function. It seems this is a case where I shouldn't try to worry about getting automatic differentiation to do something like symbolic differentiation and get an "automatic differentiation function `dfdt(u)`" because it's simply not possible and probably won't be beneficial in the end.

Thanks for walking me through this.
