### ISSUE TITLE
Using ForwardDiff with types

### ISSUE THREAD

**Issue by ranjanan** [JuliaDiff/ForwardDiff.jl#188]
Hi Jarrett,

I have question. 

Consider the following code: 
```julia
immutable thing                                                                 
    a::Float64                                                                  
    b::Float64                                                                  
    c::Int64                                                                    
    d::String                                                                   
end                                                                             
                                                                                
function blah(u::Float64, v::Float64)                                         
    x = u + 3v^2                                                                
    y = u - 2v^3                                                                
    thing(x, y, 1, "hello")                                                     
end                                                                           
                                                                                
function value(t::thing, s::Float64)                                            
    t.a + t.b - s                                                               
end    

f(x) = value(blah(1., x), 5.) 
```

Now if I did `ForwardDiff.derivative(f, 5)`, I'd get the following error:
```
ERROR: MethodError: no method matching blah(::Float64, ::ForwardDiff.Dual{1,Int64})
Closest candidates are:
  blah(::Float64, ::Float64) at /Users/ranjan/Downloads/Circuitscape-4.0.5/circuitscape/trial.jl:10
 in derivative(::#f, ::Int64) at /Users/ranjan/.julia/v0.5/ForwardDiff/src/derivative.jl:5
```
So I need to change the function signature. Next, I'd need to change the annotations within my type too (because I'd be passing `ForwardDiff.Dual{val,Float64}` there instead of `Float64`. If I do change all that though (for example, parametrize the type and say `a` and `b` have the same type, then it would create a type with Duals and I'd get a derivative (which I think is correct)

My question is: how exactly do I deal with this elegantly? I might have a complex hierarchy of types, and it's hard for me to go down the hierarchy manually and rewrite everything. 

Sorry about the long post, and thanks for your patience! :)

**Comment by KristofferC** [comment]
This is typically solved by not over typing. There is no need here why everything is hardcoded to `Float64` instead of `<:AbstractFloat`. The dual numbers need to be able to flow through the whole computation, over typing prevents that.

**Comment by jrevels** [comment]
Unfortunately, you can't really do operator-overloading-based AD unless the code is "generic enough". See the documentation [here](http://www.juliadiff.org/ForwardDiff.jl/limitations.html) for a specific description.

> instead of <:AbstractFloat

Keep in mind that the genericity requirement for `Dual` is that type/dispatch assertions can't be more restrictive than `::Real`. 

If Julia allowed us to define something like `Dual{T} <: supertype(T)`, then we could support things like `AbstractFloat` restrictions (but I'm not holding my breath for that kind of subtype relation to ever exist in Julia).
