### ISSUE TITLE
forwarddiff 0.4 news entry

### ISSUE THREAD

**Issue by mlubin** [JuliaDiff/ForwardDiff.jl#210]
There's no news entry or upgrade guide for FowardDiff 0.4. Are there any breaking changes?

**Comment by jrevels** [comment]
The minor version bump was just because we dropped Julia v0.4 support. We could add an entry to the news section saying that.

**Comment by mlubin** [comment]
That would be helpful since we put tight version bounds in ForwardDiff in JuMP
