### ISSUE TITLE
crash on windows nightly

### ISSUE THREAD

**Issue by mlubin** [JuliaDiff/ForwardDiff.jl#220]
https://ci.appveyor.com/project/JuliaOpt/jump-jl/build/1.0.14/job/bks4v0cawpga2qur#L161

Is this a known issue?

**Comment by mlubin** [comment]
(It's not obvious that ForwardDiff is even to blame)

**Comment by jrevels** [comment]
Stacktrace points to [here](https://github.com/JuliaDiff/ForwardDiff.jl/blob/v0.4.2/src/dual.jl#L195). Looks like a precompilation/type inference bug? I have no idea why that would be Windows-specific, though. Did CI on other OSes pass?

We should enable AppVeyor for ForwardDiff...

**Comment by mlubin** [comment]
Here's the corresponding PR: https://github.com/JuliaOpt/JuMP.jl/pull/1008
All OS/0.5/0.6 combinations pass except windows 0.6.

**Comment by mlubin** [comment]
Note appveyor is running julia-debug

**Comment by KristofferC** [comment]
Doesn't seem relevant anymore.
