### ISSUE TITLE
Differentiate a function with respect to a tensor

### ISSUE THREAD

**Issue by quangvunp** [JuliaDiff/ForwardDiff.jl#226]
I can calculate derivative of a function with respect to a scalar:
           x = 3
           f(x) = 4 * x 
           result = ForwardDiff.derivative(f,x)
How about the case of derivative of a function with respect to a vector?
  
This didn't work:
          x = ones(3,3)
          f(x) = x * 3
          g = x -> ForwardDiff.derivative(f,x)
          g(x)

**Comment by jrevels** [comment]
See the [API documentation](http://www.juliadiff.org/ForwardDiff.jl/basic_api.html) for the different differentiation forms that are supported (note that these docs aren't well-versioned - they only reflect ForwardDiff master, ref https://github.com/JuliaDiff/ForwardDiff.jl/issues/217). In your case, you can take the Jacobian:

```julia
julia> using ForwardDiff

julia> x = ones(3,3);

julia> f(x) = x * 3
f (generic function with 1 method)

julia> j = x -> ForwardDiff.jacobian(f,x)
(::#3) (generic function with 1 method)

julia> j(x)
9×9 Array{Float64,2}:
 3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.0
```

Note that ForwardDiff orders `jacobian` results via linear indexing of the input/output arrays, thus always yielding a matrix. If you want your result to have a different array rank, you can use `reshape`.
