### ISSUE TITLE
Preallocating vectors within function

### ISSUE THREAD

**Issue by mcovalt** [JuliaDiff/ForwardDiff.jl#242]
I have two versions of my function that I'm attempting to run ForwardDiff.jl on:

* One that is not typed and has no preallocation of vectors (every operation on a vector returns a new one). This one is very slow, but seems to work with ForwardDiff.jl
* The other is typed throughout and has every vector preallocated. This function uses in-place operations everywhere. ForwardDiff.jl does not seem to work on this function.

The preallocating function carries all of it's work vectors in a composite type. The vectors within are all typed to be either `Vector{Float64}` or `Vector{ForwardDiff.Dual{chunksize, Float64}}`. Even if a vector may not be part of the ForwardDiff calculations it is created and typed as `Vector{ForwardDiff.Dual{chunksize, Float64}}` as a matter of convenience.

Is there a way to preallocate strictly typed vectors so that they work with ForwardDiff.jl?

I referenced #136 and noticed [this comment](https://github.com/JuliaDiff/ForwardDiff.jl/issues/136#issuecomment-237916631). Perhaps I am running into perturbation confusion. This leads me to ask, why does the solution there not suffer from perturbation confusion?

**Comment by jrevels** [comment]
> Perhaps I am running into perturbation confusion. This leads me to ask, why does the solution there not suffer from perturbation confusion?

Luckily, if you're using the latest version of ForwardDiff, it is very unlikely you are running into perturbation confusion; ForwardDiff now tags dual numbers so that an explicit error will be thrown in case perturbation confusion is detected.

> Is there a way to preallocate strictly typed vectors so that they work with ForwardDiff.jl?

You can just use the same facilities one would use for caching/fetching type-generic state - functions like `similar`, `zeros`, etc. which allocate new arrays with the proper type.

If for some reason you *really* need to know exactly what element type ForwardDiff will use, you can just query the configuration object you're using for your ForwardDiff operation:

```julia
julia> cfg = ForwardDiff.GradientConfig(sum, rand(1));

# this the eltype of the input fed to `sum` when calling `ForwardDiff.gradient(sum, rand(1), cfg)`
julia> eltype(cfg)
ForwardDiff.Dual{ForwardDiff.Tag{Base.#sum,0xb046287d533b082d},Float64,1}
```

**Comment by mcovalt** [comment]
Thank you for the explanation. Apparently I was running 0.4. Still, with 0.5.0,  I am getting incorrect results with the in-place version of my function. Are there any other circumstances that may lead to incorrect results with in-place operations?

**Comment by mcovalt** [comment]
Traced it down to what I can only assume is a difference in numerical precision between the two functions. Unfortunately, the in-place function causes the AD solution to spiral out of control. Bizarre.

**Comment by jrevels** [comment]
> Traced it down to what I can only assume is a difference in numerical precision between the two functions. Unfortunately, the in-place function causes the AD solution to spiral out of control. Bizarre.

Hmm. Could you share the code you're working with, or better yet, post an [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example)?

**Comment by mcovalt** [comment]
I've tried many times to write a MWE with no success. My code is quite large and complicated, so I will just attempt to explain what it occurring.

In one part of my code a nonsymmetric linear system of equations must be solved. To do this, I am using [BiCGStab](https://en.wikipedia.org/wiki/Biconjugate_gradient_stabilized_method). The allocating version of my function builds the left hand side from 5 or so other matrices. The nonallocating version never explicitly builds the LHS, but propagates the effect of each matrix operation onto the guessed solution into buffers. The key here: the nonallocating version has many more operations directly on the Dual vector.

Although this operation occurs a few times throughout the BiCGStab method, only one of the `A*x` operations (the first) is sensitive to the following error: at one point, after 1000's of successful BiCGStab operations, the derivative of the non-allocating `A*x` operation is slightly too big. As this iterative BiCGStab is contained within another iterative process, the error starts to blow up very quickly. I am expecting derivatives in the neighborhood of 1e-8, but by the end of the non-allocating version, I get derivatives in the neighborhood of 1e300. The derivative grows to 1e6 in just a few BiCGStab iterations. I have no idea why only the one particular `A*x` operation within BiCGStab is the culprit.

My only guess is that as this is an iterative minimizing process, the operations on the very small residual vector as well as the very small partials get out of whack numerically. I can't think of any other reason.
