### ISSUE TITLE
Move `atan` and `hypot` special casing to `DiffBase.jl`?

### ISSUE THREAD

**Issue by twadleigh** [JuliaDiff/ForwardDiff.jl#249]
The resolution of  #248 would involve adding a loop over `RealInterface.BINARY_MATH` in `dual.jl` to capture new rules added in https://github.com/JuliaDiff/DiffBase.jl/issues/15. 

The other functions listed in `BINARY_MATH` (`atan` and `hypot`) are listed as TODOs in `DiffBase.jl` and currently treated as a special cases in `dual.jl`.

While adding rules to `DiffBase.jl` for `rem` and `mod`, does it make sense to move the special casing for these functions at the same time, such that they would all be serviced by the loop over `BINARY_MATH`?

I can submit a PR for this, if it is deemed a reasonable thing to do.

**Comment by jrevels** [comment]
addressed by #251
