### ISSUE TITLE
Base.Math.JuliaLibm.log1p infinite recursion

### ISSUE THREAD

**Issue by tpapp** [JuliaDiff/ForwardDiff.jl#261]
The function `Base.Math.JuliaLibm.log1p` (a more accurate, and usually faster version of `Base.log1p`) goes into infinite recursion when used with `ForwardDiff.Dual`s. MWE:

```julia
julia> using ForwardDiff

julia> Base.Math.JuliaLibm.log1p(ForwardDiff.Dual(1.0,1.0))
VERSION
ERROR: StackOverflowError:
Stacktrace:
 [1] log1p(::ForwardDiff.Dual{Void,Float64,1}) at ./special/log.jl:395 (repeats 80000 times)

julia> VERSION
v"0.6.0"

julia> Pkg.status("ForwardDiff")
 - ForwardDiff                   0.5.0
```

**Comment by jrevels** [comment]
Looks like `Base.Math.JuliaLibm.log1p(x::Real)` just calls `Base.Math.JuliaLibm.log1p(float(x))`, which basically guarantees infinite recursion in the general case  (e.g. `T = typeof(float(x)); T <: Real && !(T <: Float64) && !(T <: Float32)`).

Easiest solution would be to add a rule for `Base.Math.JuliaLibm.log1p` to [DiffRules](https://github.com/JuliaDiff/DiffRules.jl).

**Comment by tpapp** [comment]
Closed by https://github.com/JuliaDiff/DiffRules.jl/pull/8.
