### ISSUE TITLE
Jacobian-vector product

### ISSUE THREAD

**Issue by mcovalt** [JuliaDiff/ForwardDiff.jl#263]
It would be nice to be able to calculate the Jacobian-vector product as described in [this paper](https://arxiv.org/pdf/1502.05767.pdf) at the top of page 10.

For example, If I'm reading it correctly, to find `F'(x)*p` just evaluate `F(v)`  where `v` is a vector of `Dual`'s with the `value` set to `x` and a single partial set to `p`.

**Comment by jrevels** [comment]
Yup - this is a dup of https://github.com/JuliaDiff/ForwardDiff.jl/issues/43
