### ISSUE TITLE
Hessian of 4x4 matrix multiplication using StaticArrays brings Julia to its knees

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiff/ForwardDiff.jl#266]
Probably an issue for Julia itself, but still.

```julia
julia> using ForwardDiff, StaticArrays

julia> function g(x)
           y = eye(SMatrix{4, 4})
           z = SMatrix{4, 4}(reshape(x, 4, 4))
           (y * z)[1]
       end
g (generic function with 1 method)

julia> ForwardDiff.hessian(g, rand(16))
```
results in 100% CPU usage until I forcibly kill Julia.

```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

```julia
julia> Pkg.status()
3 required packages:
 - ForwardDiff                   0.6.0              master
 - Revise                        0.0.9
 - StaticArrays                  0.6.2
10 additional packages:
 - BinDeps                       0.7.0
 - CommonSubexpressions          0.0.1
 - Compat                        0.32.0
 - DataStructures                0.7.2
 - DiffResults                   0.0.1
 - DiffRules                     0.0.1
 - NaNMath                       0.2.6
 - SHA                           0.5.1
 - SpecialFunctions              0.3.3
 - URIParser                     0.2.0
```
ForwardDiff sha: 1129f9be2b706e52a430d5b29f7ddf41bb49ca18.

**Comment by tkoolen** [comment]
(Updated example so that it actually returns a scalar)

**Comment by KristofferC** [comment]
Yeah, I usually use second derivatives of 3x3 matrices and first call can be up to 10 seconds. I can imagine 4x4 be quite bad (81 partials vs 256 partials).

**Comment by KristofferC** [comment]
As a workaround,  you can use a smaller chunk side.

**Comment by tkoolen** [comment]
> smaller chunk side

Yeah, that's what I've been doing. But it's still kind of scary that the default chunk size just brings down Julia's compiler, even with such an innocent-looking function. Perhaps the default chunk size for Hessians should be much smaller (maybe even 1)?

**Comment by jrevels** [comment]
> Perhaps the default chunk size for Hessians should be much smaller (maybe even 1)?

With all the inference performance problems Hessians have given us in the past, this seems like a reasonable change.

To be fair to Julia's compiler, ForwardDiff does ask it to do a lot of work by inlining everything and exposing so much type info...poor little guy gets tired after a long day of JITing :(

**Comment by ChrisRackauckas** [comment]
Looks like the tuple length changes https://github.com/JuliaLang/julia/pull/27398 might've fixed this?

```julia
using ForwardDiff, StaticArrays,LinearAlgebra

function g(x)
  y = SMatrix{4, 4}(Array(I,4,4))
  z = SMatrix{4, 4}(reshape(x, 4, 4))
  (y * z)[1]
end

@time ForwardDiff.hessian(g, rand(16))
# 12.102456 seconds (6.85 M allocations: 377.719 MiB, 1.63% gc time)
```

**Comment by KristofferC** [comment]
Closing as a (close) dup of https://github.com/JuliaDiff/ForwardDiff.jl/issues/278
