### ISSUE TITLE
Wrong forwarddiff numerics after upgrade

### ISSUE THREAD

**Issue by papamarkou** [JuliaDiff/ForwardDiff.jl#271]
The recent changes in Julia's autodiff packages cause breakages with unclear origin. The code runs, but I get erratic numerical output in Klara (chains not converging etc) - everything was fine before the upgrade to ForwardDiff 0.6.0. Since there is no runtime error and the structure of my package doesn't justify the changes in the output I see, I can't tell at all what is going on from the ForwardDiff's side. Where can I possibly start to resolve this black box of autodiff chaos without seeing any runtime warnings of errors? Has memory allocation or autodiff value storage changed somehow for instance?

**Comment by ChrisRackauckas** [comment]
On the other end, I got spurious errors with the update (https://github.com/JuliaDiff/ForwardDiff.jl/issues/270 ) and the upgrade broke 3 packages I have which are dependencies. It might be good to let downstream packages know that this has happened, and add some upper bounds by default.

**Comment by jrevels** [comment]
> Where can I possibly start to resolve this black box of autodiff chaos without seeing any runtime warnings of errors?

Can you please post an [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example)?

> It might be good to let downstream packages know that this has happened, and add some upper bounds by default.

Maintainers should always feel free to add upper bounds to their packages to future-proof against upstream breakage (though it's unfortunate that the METADATA upper-bounding process can be painful). Note that the only API change in ForwardDiff v0.6 is listed in ForwardDiff's [upgrade guide](http://www.juliadiff.org/ForwardDiff.jl/stable/user/upgrade.html), which is linked to by the `News` section of the README. Also note that there is at least one minor release cycle for deprecation before that change actually breaks downstream code. Bugs, of course, are unintentional 😛

**Comment by scidom** [comment]
Thanks @jrevels, @ChrisRackauckas. I will try to create a simple example (independent of my own package) and will post here if I succeed.

**Comment by KristofferC** [comment]
This seems stale.
