### ISSUE TITLE
Incorrect promotion during division

### ISSUE THREAD

**Issue by MikeInnes** [JuliaDiff/ForwardDiff.jl#272]
```julia
julia> ForwardDiff.Dual(1f0)/2 |> typeof
ForwardDiff.Dual{Void,Float64,0}

julia> 1f0/2 |> typeof
Float32
```

I'm not sure where this is coming from, as other operators work correctly and the DiffRules expression doesn't seem to be causing an issue.

**Comment by fredrikekre** [comment]
#264

**Comment by MikeInnes** [comment]
Ah, I see that a checkout fixes it. Thanks!
