### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiff/ForwardDiff.jl#282]
I ran into https://github.com/JuliaDiff/ForwardDiff.jl/issues/264, which makes 0.6.0 unusable for me. Would you mind tagging a new version? Thanks!

**Comment by ChrisRackauckas** [comment]
I think it's waiting on https://github.com/JuliaDiff/ForwardDiff.jl/pull/279

**Comment by jrevels** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/12105

**Comment by tkoolen** [comment]
Thank you!
