### ISSUE TITLE
Allow functions that also accept parameters in the differentiation API?

### ISSUE THREAD

**Issue by Datseris** [JuliaDiff/ForwardDiff.jl#296]
Are there any plans to also allow functions of the form `f(u, p)` with `p` some parameter container used in the model?

e.g. from the documentation of `jacobian!`:

> Compute J(f) evaluated at x and store the result(s) in `result`, assuming `f` is called as `f(x)`. This method assumes that `isa(f(x), AbstractArray)`.

to be extended to:

Compute J(f) evaluated at x and store the result(s) in `result`, assuming `f` is called as `f(x, p)`. This method assumes that `isa(f(x, p), AbstractArray)`.

**Comment by Datseris** [comment]
Why was this issue created, when I can just use closures?

because
```julia
function DiscreteDS(u0::AbstractVector, eom; parameters = nothing)
    su0 = SVector{length(u0)}(u0)
    reducedeom(x) = eom(x, parameters)
    cfg = ForwardDiff.JacobianConfig(eom, u0)
    @inline ForwardDiff_jac(x) = ForwardDiff.jacobian(eom, x, cfg)
    return DiscreteDS(su0, eom, ForwardDiff_jac)
end
```
and
```julia
mutable struct DiscreteDS{D, T<:Number, F, J, P} <: DiscreteDynamicalSystem
    state::SVector{D,T}
    eom::F
    jacob::J
    p::P
end
```
the Problem is that if somebody changes `p` inside an instance of `DiscreteDS` (not mutate in place, but directly replace the entire thing)
the closure will not have the change.

**Comment by jrevels** [comment]
AFAICT, the only differences between the closure-based approach (what ForwardDiff requires of people now) and the argument-based approach (this feature request) are superficial, i.e. I'm pretty sure one could just write a macro/function that provides a one-to-one translation. 

> the Problem is that if somebody changes p inside an instance of DiscreteDS (not mutate in place, but directly replace the entire thing)
> the closure will not have the change.

This isn't a ForwardDiff problem, though; you just need close over the object you actually wish to capture, instead of only closing over the binding to it. For your example, IIUC, you should be closing over the produced `DiscreteDS` instance + performing a field access on `p` rather than closing over the `parameters` binding.

**Comment by Datseris** [comment]
Thanks for the comments. I can't close over the `DiscreteDS` instance because the Jacobian function has to be a field of it. 

But I get your point so I will see if I can try something else.

**Comment by jrevels** [comment]
> I can't close over the DiscreteDS instance because the Jacobian function has to be a field of it.

You can, though. You can make an instance of the object, then set the field to the Jacobian function you want, e.g.  

```
julia> mutable struct Foo
           x::Int
           function Foo(x)
               f = new()
               f.x = x+1
               return f
           end
       end

julia> Foo(4)
Foo(5)
```

You might have to make the function its own type so you know beforehand how to instantiate the object, though. Or, it might be easier though just to close over a `Ref` and have the API for changing `parameters` be to alter the `Ref` instead of touching the field directly.

**Comment by Datseris** [comment]
Thanks a lot for helping, even though you don't have to; I appreciate it.

I will try this at some point in the near future and *if* I succeed, I will report it here for archival reasons.

**Comment by Datseris** [comment]
Hi, I have managed to solve this!

I only now have the problem that I cannot use `JacobianConfig`.

Long story short, here is my attempt:
```julia
    dum = deepcopy(prob.u0)
        cfg = ForwardDiff.JacobianConfig(
            (y, x) -> prob.f(y, x, prob.p, prob.tspan[1]),
            dum, prob.u0)
        jacobian = (J, u, p, t) ->
        ForwardDiff.jacobian!(J, (y, x) -> prob.f(y, x, p, t), dum, u, cfg)
```
there isn't any config I could use, I get an error that says `Invalid Tag Object`.

My only question is: Is this a big hit to performance? Not having the config?

If yes, how can I battle it?

**Comment by Datseris** [comment]
@ChrisRackauckas thanks for the feedback. I tried it and works for in-place Jacobians. For out-of-place however, there seems to be some kind of fundamental issue that I don't understand.

Specifically, let `prob` be any out-of-place problem where `f` returns `SVector`. Then, look the following MWE:

```julia
@inline @inbounds function loop(u, p, t)
    σ = p[1]; ρ = p[2]; β = p[3]
    du1 = σ*(u[2]-u[1])
    du2 = u[1]*(ρ-u[3]) - u[2]
    du3 = u[1]*u[2] - β*u[3]
    return SVector{3}(du1, du2, du3)
end

prob = ODEProblem(loop, rand(SVector{3}), (0.0, 10.0), [10, 28, 8/3])

jac = (u, p, t) -> ForwardDiff.jacobian((x) -> prob.f(x, p, t), u)
jac(prob.u0, prob.p, 1.0) # Returns SMatrix

cfg = ForwardDiff.JacobianConfig((x) -> prob.f(x, prob.p, prob.tspan[1]), prob.u0)
jac = (u, p, t) -> ForwardDiff.jacobian((x) -> prob.f(x, p, t), u, cfg, Val{false}())
jac(prob.u0, prob.p, 1.0) # returns Matrix (loses SMatrix for some reason)
```

**Comment by ChrisRackauckas** [comment]
@simonbyrne did the tagging stuff so maybe he can comment. That looks like a bug.

**Comment by simonbyrne** [comment]
Ah, it's because `SArray` stuff doesn't actually need the tags, so I never added methods to disable them.

**Comment by Datseris** [comment]
You are right! I just checked and the out-of-place methods that use `SVector` can accept `JacobianConfig` without a problem!

**Comment by ChrisRackauckas** [comment]
And configs aren't needed with static arrays since there's no real cache. So, that's fine.

**Comment by Datseris** [comment]
So, to be sure I am doing stuff correctly:
`ForwardDiff.jacobian((x) -> prob.f(x, p, t), u, cfg)` here I *should not* use `cfg` if the function used returns `SVector` ?

**Comment by simonbyrne** [comment]
you can keep it: it is just ignored. (so keep it if you're planning on using non-static vectors)
