### ISSUE TITLE
ForwardDiff.gradient fails on loglikelihood of TDist

### ISSUE THREAD

**Issue by atteson** [JuliaDiff/ForwardDiff.jl#314]
ForwardDiff seems to fail on the loglikelihood of TDist as demonstrated by the code below.  This doesn't seem to be a problem with the basic machinery of Distributions since it works with, for example, Normal as can be seen by removing the comment below.  TDist is a smooth distribution with a simple density function and so should be differentiable.  The density function has the gamma function in it so the loglikelihood has the log of the gamma function but this function seems to work fine in ForwardDiff.gradient.

```julia
using Distributions
using ForwardDiff

dist = TDist
#dist = Normal

td = dist(3.0)
sample = rand(td, 100)
g(x) = loglikelihood( dist(x...), sample )
ForwardDiff.gradient( g, [3.0] )
```

**Comment by KristofferC** [comment]
Seems to work fine now

```
julia> ForwardDiff.gradient( g, [3.0] )
1-element Array{Float64,1}:
 1.2306836186341163
```
