### ISSUE TITLE
define typemin and typemax?

### ISSUE THREAD

**Issue by sglyon** [JuliaDiff/ForwardDiff.jl#318]
When using `maximum(::Array, ::Int)` with ForwardDiff, I get nasty errors saying `Base.typemin` is not defined.

As a stop-gap I just define it like this:

```julia
function Base.typemin(::Type{ForwardDiff.Dual{T,V,N}}) where {T,V,N}
    ForwardDiff.Dual{T,V,N}(typemin(V))
end
```

in my code, but that function probably really belongs here.

I would open a PR, but I'm not sure exactly where in dual.jl it belongs (e.g. which section of that file, so things stay organized) as well as whether or not it should be `@inline`d. Any suggestions?

**Comment by matbesancon** [comment]
bump on this? I just hit the same error
