### ISSUE TITLE
Sign error on derivatives with certain type of functions.

### ISSUE THREAD

**Issue by KristofferC** [JuliaDiff/ForwardDiff.jl#33]
Am I doing something forbidden here?

```julia
# Simple working example
f(x) = x[1]^2
g = forwarddiff_gradient(f, Float64, fadtype=:typed)
g([3.0])
# 6.0, OK!

# But rewrite it in this way:
f(x) = [x[1]^2]' * [1.0]
g = forwarddiff_gradient(f, Float64, fadtype=:typed)
g([3.0])
 # -6.0, Wups!
```

Edit: Oh, this is almost exactly: https://github.com/JuliaDiff/ForwardDiff.jl/issues/24 but it should have been fixed in https://github.com/JuliaDiff/ForwardDiff.jl/pull/25?

Edit2: Looked into it a bit more, the problem is not with transpose but with conjugate:

```julia
A = ForwardDiff.GraDual{Float64,1}[GraDual(3.0, [1.0])]

julia> A'*[1.0]
1-element Array{ForwardDiff.GraDual{Float64,1},1}:
 GraDual(3.0,
[-1.0])

julia> A.'*[1.0]
1-element Array{ForwardDiff.GraDual{Float64,1},1}:
 GraDual(3.0,
[1.0])
```

Basically, why does conj on a `Array{ForwardDiff.GraDual{Float64,1},1}` invert the gradient part?

**Comment by mlubin** [comment]
Could you give this a try with #27? That branch basically fixes everything.

**Comment by KristofferC** [comment]
Yeah, looks like this is correct: https://github.com/JuliaDiff/ForwardDiff.jl/pull/27/files#diff-85b7db0a1fe4b76c8f248e5b5d9ad774R71

Using the matrix syntax doesn't work but rewriting it with `dot` fixes it.

```julia
f(x) = [x[1]^2]' * [1.0]
ForwardDiff.gradient(f, [3.0])
#ERROR: MethodError: `load_gradient` has no method matching #load_gradient(::Array{ForwardDiff.GradientNum{1,Float64,Tuple{Float64}},1})
# in take_gradient at /home/kristoffer/.julia/v0.4/ForwardDiff/src/fad_api.jl:73
# in gradient at /home/kristoffer/.julia/v0.4/ForwardDiff/src/fad_api.jl:78

f(x) = dot([x[1]^2], [1.0])
ForwardDiff.gradient(f, [3.0])
# 1-element Array{Float64,1}:
# 6.0
```

**Comment by jrevels** [comment]
> Using the matrix syntax doesn't work but rewriting it with dot fixes it.
> 
> f(x) = [x[1]^2]' * [1.0]

Just a note on why this results in an error: `f` above is a function from a `Vector` to a `Vector` - `ForwardDiff.gradient` expects a function from a `Vector` to a `Number`.

**Comment by KristofferC** [comment]
Ah, of course, thank you for pointing that out.
