### ISSUE TITLE
Calculating the Jacobian of a gradient

### ISSUE THREAD

**Issue by salbert83** [JuliaDiff/ForwardDiff.jl#338]
Consider the following run under Julia 0.6.4
------------------------------------------
using ForwardDiff

function grad_test_1(x)
    v = zeros(4)
    ForwardDiff.gradient!(v, x -> 0.5sum(x.^2), x)
    v[end] = sum(log.(x))
    return v
end

function grad_test_2(x)
    return push!(ForwardDiff.gradient(x -> 0.5sum(x.^2), x), sum(log.(x)))
end

x = 2.0ones(3)

@show grad_test_2(x)
@show ForwardDiff.jacobian(grad_test_2, x)

@show grad_test_1(x)
@show ForwardDiff.jacobian(grad_test_1, x)

-----------------------------------------------------------------------
I get the following on execution:
------------------------------------------------------
grad_test_2(x) = [2.0, 2.0, 2.0, 2.07944]
ForwardDiff.jacobian(grad_test_2, x) = [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0; 0.5 0.5 0.5]
grad_test_1(x) = [2.0, 2.0, 2.0, 2.07944]
ERROR: LoadError: MethodError: Cannot `convert` an object of type ForwardDiff.Dual{ForwardDiff.Tag{#
grad_test_1,Float64},Float64,3} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.

Why does this work for grad_test_2 but not grad_test_1?

**Comment by Gnimuc** [comment]
that's because `v`'s type is restricted  to `Float64`, try this:
```julia
function grad_test_1(x::T)
v = zeros(T, 4)
```

**Comment by Gnimuc** [comment]
that's because `v` is restricted to `Float64`, try this instead:
```julia
function grad_test_1(x::Vector{T}) where {T<:Real}
       v = zeros(T, 4)
       ForwardDiff.gradient!(v, x -> 0.5sum(x.^2), x)
       v[end] = sum(log.(x))
       return v
end
```

**Comment by jrevels** [comment]
@Gnimuc answer is correct (thanks!).

**Comment by salbert83** [comment]
Perfect!  Thanks you!
