### ISSUE TITLE
question: value & jacobian of function that returns vector and something else

### ISSUE THREAD

**Issue by tpapp** [JuliaDiff/ForwardDiff.jl#355]
I have a function that calculates a mapping from a vector of reals to another of the same dimension, and at the same time produces some interim results that are otherwise expensive to compute, so I want to get them too. MWE:
```julia
f(x) = x.^2, sqrt.(x)
```
I want to be able to use the `DiffResults.JacobianResult` interface to get value & Jacobian in one step, instead of
```julia
f(x), ForwardDiff.jacobian(first ∘ f, x)
```
Is this possible?

**Comment by KristofferC** [comment]
Close over a ` Ref`, update the `Ref` in the function (possibly only if the input number is a `Real`, return only the function value, but you can then extract the result from the mutated `Ref`?

**Comment by jrevels** [comment]
Yeah, Kristoffer's solution is the main way of doing this in ForwardDiff; basically anything that doesn't conform to the exact functional API has to be done via closures and side-effects. 

(sorry, I know it's painful; I'm trying to design something less annoying for future AD work)
