### ISSUE TITLE
Caching results for non-square Jacobian fails

### ISSUE THREAD

**Issue by ahojukka5** [JuliaDiff/ForwardDiff.jl#359]
I think there's a bug when trying to use DiffResults to get lower order results when Jacobian is not square matrix. Here's a MWE:

```julia
using ForwardDiff
f(x) = [x[1]+x[2], x[3]*x[4], x[5]^x[6]]
x = rand(6)
J = ForwardDiff.jacobian(f, x) # => 3x6 array
result = DiffResults.JacobianResult(x)
ForwardDiff.jacobian!(result, f, x)
```

The last function call fails to dimension mismatch.

**Comment by KristofferC** [comment]
I think you need to give both input and output size like the second docstrings in http://www.juliadiff.org/DiffResults.jl/latest/#DiffResults.JacobianResult shows.

**Comment by ahojukka5** [comment]
Yes, it looks that this was a user error. I close this.
