### ISSUE TITLE
`ForwardDiff.derivative(float, 1)` returns `Float16(1.0)`

### ISSUE THREAD

**Issue by cossio** [JuliaDiff/ForwardDiff.jl#362]
Why the conversion to `Float16`? This only occurs with integer `1`. 

`ForwardDiff.derivative(float, 1.0)` works fine.

**Comment by KristofferC** [comment]
Was added here https://github.com/JuliaDiff/ForwardDiff.jl/pull/102/files#diff-4219ec6c9cb995350a377a82553b738bR161.
