### ISSUE TITLE
derivative(xlogx, 0.) gives 0 (should be -Inf)

### ISSUE THREAD

**Issue by cossio** [JuliaDiff/ForwardDiff.jl#365]
Consider the definition of `xlogx`:

https://github.com/JuliaStats/StatsFuns.jl/blob/7473d0d8f7c5b2f4a53f0625ada5f2323c84ffe4/src/basicfuns.jl#L14

```julia
xlogx(x::Real) = x > zero(x) ? x * log(x) : zero(log(x))
```

Then `derivative(xlogx, 0.)` returns `0.`. The correct answer is `-Inf`.

I understand this is due to the singular branch at `x=0`, and I'm not even sure if there is any way that `ForwardDiff` can handle this.

**Comment by andreasnoack** [comment]
You can add it as a rule for `xlogx` in https://github.com/JuliaDiff/DiffRules.jl. See e.g. https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl#L14

**Comment by devmotion** [comment]
The rules for `xlogx`  and other functions from LogExpFunctions were added to DiffRules a while ago.
