### ISSUE TITLE
`f(x::Real) = f(float(x))` leads to stackoverflow

### ISSUE THREAD

**Issue by cossio** [JuliaDiff/ForwardDiff.jl#366]
Many definitions follow this pattern:
```
f(x::AbstractFloat) = 2x # any computation here
f(x::Real) = f(float(x))
```

But then:

```
julia> ForwardDiff.derivative(f, 1.)
ERROR: StackOverflowError:
Stacktrace:
 [1] f(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(f),Float64},Float64,1}) at ./REPL[3]:1 (repeats 80000 times)
```

Because `float(Dual)` gives `Dual` which is not `AbstractFloat`. Is there a way around this?

**Comment by cossio** [comment]
I did not realize this was being discussed elsewhere

https://github.com/JuliaLang/julia/issues/26552
https://github.com/JuliaDiff/ForwardDiff.jl/issues/261
https://github.com/JuliaDiff/ForwardDiff.jl/issues/324
https://github.com/musm/SLEEF.jl/issues/11

**Comment by DilumAluthge** [comment]
This is a known limitation of ForwardDiff.jl:
http://www.juliadiff.org/ForwardDiff.jl/latest/user/limitations.html

The only ways around this that I can think of will come from either
Cassette.jl/Capstan.jl or Zygote.jl.

**Comment by DilumAluthge** [comment]
My apologies, I misunderstood your issue. Thanks for posting the correct
issue links.
