### ISSUE TITLE
Jacobian of function that solves an ODE internally

### ISSUE THREAD

**Issue by astrorCoder** [JuliaDiff/ForwardDiff.jl#397]
I am trying to compute the jacobian of a function that solves an Ode internally (using DiffEquations.jl), the function has the following structure:

`function fConstraint(x::Vector)::Vector
    sol = calc_data(x) #ode solving
    #println(x)
    res = [  sol[1][2]-data["hgoal"]*1e3/datos_prob["r12"],
               -sol[1][2],
                sol[2][2]+data["tspan"][2]*0.99,
              -sol[1][1]+data["hmmin"]*1e3/datos_prob["r12"] ]
end`

The function is used to compute the restrictions in an optimization problem, and I am using a solver that requires the gradient of the constraints. Is there a way to do this with ForwardDiff? I ask because I get an enormous error code that starts like this:

ForwardDiff.jacobian(fConstraint, [0.001,0.1,0.1])
ERROR: MethodError: no method matching Float64(::ForwardDiff.Dual{ForwardDiff.Tag{typeof(fConstraint),Float64},Float64,3})
Closest candidates are:
  Float64(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:194
  Float64(::T<:Number) where T<:Number at boot.jl:741
  Float64(::Int8) at float.jl:60
  ...

, and I guess it is because of the internal ode, otherwise it is a very simple function and it computes without problems (I have tried with another much simpler function that only uses sums and it computes the jacobian well).

Thanks in advance :)

**Comment by astrorCoder** [comment]
The code doen't look well sorry, it is more like:

**_function fConstraint(x::Vector)::Vector
    sol = calc_data(x)
    #println(x)
    res = [ sol[1][2]-data["hgoal"]*1e3/datos_prob["r12"],
            -sol[1][2],
            sol[2][2]+data["tspan"][2]*0.99,
            -sol[1][1]+data["hmmin"]*1e3/datos_prob["r12"] ]
end_**

**Comment by ChrisRackauckas** [comment]
I have no idea what you're asking. Do you have code that can be ran?

**Comment by astrorCoder** [comment]
This code shows what I was trying to explain:
[testJacobian.jl.zip](https://github.com/JuliaDiff/ForwardDiff.jl/files/2935127/testJacobian.jl.zip)
Thank you very much for taking interest¡

**Comment by ChrisRackauckas** [comment]
You're trying to autodiff a code with a continuous callback, which means that time points at which things occur is differentiable too, and you have to make sure that time is Dual in that case. You do this by making `tspan` be `convert.(eltype(x),data["tspan"])`. This fixes the errors.

**Comment by astrorCoder** [comment]
> You're trying to autodiff a code with a continuous callback, which means that time points at which things occur is differentiable too, and you have to make sure that time is Dual in that case. You do this by making `tspan` be `convert.(eltype(x),data["tspan"])`. This fixes the errors.

Thank you very much!. I would have never figured that out by myself. Does the change have any effect on performance (ODE-wise)?

**Comment by ChrisRackauckas** [comment]
Just compile time.
