### ISSUE TITLE
Extra allocations when function has method that allows ForwardDiff argument

### ISSUE THREAD

**Issue by astrorCoder** [JuliaDiff/ForwardDiff.jl#398]
So I have to use a very simple function that can be written in a way that doesn't allocate, it looks like this:

```Julia
using BenchmarkTools

y0 = [0.5,0.2,-0.1]

calcDists(y::Array{Float64,1})    = sqrt((y[1]-0.1)^2+y[2]^2+y[3]^2)

@btime calcDists(y0)
```

The benchmark tells what I would expect:
```Julia
julia> @btime calcDists(y0)
  4.499 ns (0 allocations: 0 bytes)
```
The thing is that this function is going to be `ForwardDiff` (sometimes) when I use it inside a bigger function, so I thought of using multiple dispatch and add another method compatible with the Dual number that is going to be entering there:

```Julia
calcDists(y::Vector)              = sqrt((y[1]-0.1)^2+y[2]^2+y[3]^2) # Add second method

@btime calcDists(y0)
```
This time there is an allocation and it makes the run a bit slower:
```Julia
julia> @btime calcDists(y0)
  8.038 ns (1 allocation: 16 bytes)
```
Which is still faster than with no type specification at all. I know that there is very little difference, but I figured I ask so at least I learn something. Is this a limitation of multiple dispatch or am I doing something wrong?

**Comment by KristofferC** [comment]
Use

```
const y0 = [0.5,0.2,-0.1]
```

**Comment by astrorCoder** [comment]
> Use
> 
> ```
> const y0 = [0.5,0.2,-0.1]
> ```

Ok that did the trick, but I'm afraid that I don't know why. Still, that will help me better understand how Julia works, thanks :)
