### ISSUE TITLE
No-overhead one-pass calculation of value and derivative(s)

### ISSUE THREAD

**Issue by asprionj** [JuliaDiff/ForwardDiff.jl#401]
I have a problem with a quite simple scalar function, of which I also need the derivative together with its value. This evaluation of value and derivative is called many times (simulation). Now, I could come up with the explicit derivative of this function. But there's many such functions (so I don't want to do this for all of them) and in the end, `ForwardDiff` should be more efficient because it can calculate value and derivative in one pass instead of calls to two functions.

AFAIK there is no simple / straightforward way of doing something like
```julia
val, der = ForwardDiff.derivative(f, x)
```
right? (Also see request in #391.) Here, the focus is not on syntax only, but on the fact that also the value is actually calculated, but not directly returned. To extract value and derivative of a single pass, one would have to use `DiffResults`. But I found that there's a huge overhead with that, expecially for very simple functions. I did some benchmarking. Using the polynomial function (similar to what I deal with):
```julia
using ForwardDiff
using DiffResults

# function and explicit derivative
f(x)  = 0.1 + (0.5 + (0.7 + (0.2 - 0.05*x)*x)*x)*x
f′(x) =        0.5 + (1.4 + (0.6 - 0.20*x)*x)*x
```
I define three versions of calculating value and derivative, actually providing the simple syntax outlined above:
```julia
# value and derivative in one pass, using DiffResults
function val_der(f, x)
    res = DiffResults.DiffResult(x, (x,))
    res = ForwardDiff.derivative!(res, f, x)
    return (DiffResults.value(res), DiffResults.derivative(res))
end

# value by function call, derivative by ForwardDiff
val_der_sep(f, x) = (f(x), ForwardDiff.derivative(f,x))

# value and (manually derived) derivative by function calls
val_der_expl(f, f′, x) = (f(x), f′(x))
```
Then, for the benchmarks:
```julia
using BenchmarkTools
x = 3.4

println("f(x):")
@btime f(x)

println("f′(x):")
@btime f′(x)

println("val_der(f,x):")
@btime val_der(f, x)

println("val_der_sep(f,x):")
@btime val_der_sep(f, x)

println("val_der_expl(f, f′, x):")
@btime val_der_expl(f, f′, x)
```
On my machine, the results are (best of 3 runs for each one):
```
f(x):
  14.407 ns (1 allocation: 16 bytes)
f′(x):
  14.406 ns (1 allocation: 16 bytes)
val_der(f,x):
  278.916 ns (6 allocations: 144 bytes)
val_der_sep(f,x):
  15.515 ns (1 allocation: 32 bytes)
val_der_expl(f, f′, x):
  16.346 ns (1 allocation: 32 bytes)
```
Interpreting this:

- There's quite some benchmarking overhead compared to the actual function evaluations.
- Explicit function for the derivative and using `ForwardDiff.derivative` are very close. Any idea how to more accurately benchmark those against each other?
- The solution using `DiffResults` is a very bad idea for such tiny functions.

So, is there a way to also return the value (or, on request / by macro / etc., all intermediate derivatives calculated anyways) on the low-level / internal API of `ForwardDiff`?

**Comment by asprionj** [comment]
FYI, the above benchmarks I ran with `-O=3`, with `-O=0` the differences become a bit clearer for all the fast versions:
```
f(x):
  17.454 ns (1 allocation: 16 bytes)
f´(x):
  16.623 ns (1 allocation: 16 bytes)
val_der(f,x):
  276.124 ns (6 allocations: 144 bytes)
val_der_sep(f,x):
  20.225 ns (1 allocation: 32 bytes)
val_der_expl(f, f´, x):
  20.779 ns (1 allocation: 32 bytes)
```

**Comment by KristofferC** [comment]
This is a benchmarking artifact (https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#interpolating-values-into-benchmark-expressions).

```
julia> @code_warntype val_der(f, 2.0)
Body::Tuple{Float64,Float64}
1 ─ %1  = (Base.mul_float)(0.05, x)::Float64
│   %2  = (Base.mul_float)(1.0, 0.05)::Float64
│   %3  = (Base.sub_float)(0.2, %1)::Float64
│   %4  = (Base.neg_float)(%2)::Float64
│   %5  = (Base.mul_float)(%3, x)::Float64
│   %6  = (Base.mul_float)(x, %4)::Float64
│   %7  = (Base.mul_float)(%3, 1.0)::Float64
│   %8  = (Base.add_float)(%6, %7)::Float64
│   %9  = (Base.add_float)(0.7, %5)::Float64
│   %10 = (Base.mul_float)(%9, x)::Float64
│   %11 = (Base.mul_float)(x, %8)::Float64
│   %12 = (Base.mul_float)(%9, 1.0)::Float64
│   %13 = (Base.add_float)(%11, %12)::Float64
│   %14 = (Base.add_float)(0.5, %10)::Float64
│   %15 = (Base.mul_float)(%14, x)::Float64
│   %16 = (Base.mul_float)(x, %13)::Float64
│   %17 = (Base.mul_float)(%14, 1.0)::Float64
│   %18 = (Base.add_float)(%16, %17)::Float64
│   %19 = (Base.add_float)(0.1, %15)::Float64
│   %20 = (Core.tuple)(%19, %18)::Tuple{Float64,Float64}
└──       return %20
```
