### ISSUE TITLE
Bug in particular case of determinant function

### ISSUE THREAD

**Issue by JMmontilla** [JuliaDiff/ForwardDiff.jl#403]
I was getting a weird Method error when computing the ForwardDiff of the determinant, I have pinned it down to the particular case of the matrix being triangular, in which case the `det` function tries to convert the value of `det` before returning it. I have made this example in which I force the error:

```julia
using ForwardDiff, LinearAlgebra

A = zeros(Real,2,2)
function inter(M,x)
    a = x[1]
    b = x[2]
    M[1,1] = a^2-1.0
    M[1,2] = a-b-b^3
    M[2,1] = a*b
    M[2,2] = a-b
    nothing
end
function my_fun(M,x)
    inter(M,x)
    M[2,1] = 0.0 # Modification of M to make it triangular
    return det(M)
end

der = ForwardDiff.gradient(x -> my_fun(A,x), rand(2))
```

This is the method that causes the problem:

```julia
function det(A::AbstractMatrix{T}) where T
    if istriu(A) || istril(A)
        S = typeof((one(T)*zero(T) + zero(T))/one(T))
        return convert(S, det(UpperTriangular(A))) # Error here when trying to convert the Dual
    end
    return det(lu(A; check = false))
end
```

**Comment by KristofferC** [comment]
This seems more like a bug in the `det` method`. It's not correct to assume that you can convert to `S` based on that computation. For example, here `T` is `Real` and `one(T)` is `1`. Doesn't mean that the result of the `det` computation can be converted to a Float64.

**Comment by JMmontilla** [comment]
You are right. Should I put this in another place? (I'm new to julia so I wouldn't know where, maybe in the Julia Language Github?)

**Comment by KristofferC** [comment]
You could put this on the julia issue tracker.
