### ISSUE TITLE
Hessian is wrong with intervals

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiff/ForwardDiff.jl#411]
```jl
julia> using IntervalArithmetic, ForwardDiff, StaticArrays

julia> f(X) = ( (x, y) = X; x^2 + y^2 )
f (generic function with 2 methods)

julia> ForwardDiff.hessian(f, SVector(0..0, 0..0))
2×2 SArray{Tuple{2,2},Interval{Float64},2,4} with indices SOneTo(2)×SOneTo(2):
 [0, 2]  [0, 0]
 [0, 0]  [0, 2]
```

(Note that these are intervals being printed, not arrays.)
The diagonal entries are incorrect: they should be `2..2`.

Cf. the same problem in
https://github.com/JuliaDiffEq/SparseDiffTools.jl/issues/67

**Comment by KristofferC** [comment]
Is this claiming to be a bug in ForwardDiff? As the code is posted right now, ForwardDiff is not imported, and no function from ForwardDiff is being called.

**Comment by ChrisRackauckas** [comment]
ForwardDiff does the same exact thing with its way of seeding the Jacobian, i.e. `ForwardDiff.jacobian` gives the same result. Why ForwardDiff's Dual numbers do this is something we weren't able to determine. Note that directly calculating Hessian-vector products against basis vectors gives the correct result, so it's quite puzzling.

**Comment by KristofferC** [comment]
I just want a bug report towards a package to be written using the package API (or at leat some some attempt at doing so). As the issue is written right now a maintainer would be very tempted to close and say to report this to SparseDiffTools.

> `ForwardDiff.jacobian` gives the same result.

Would be good to see the code for this then.

**Comment by dpsanders** [comment]
Sorry about that. The code is now correct.

**Comment by KristofferC** [comment]
Can't repro:

```jl
julia> using IntervalArithmetic, ForwardDiff, StaticArrays

julia> f(X) = ( (x, y) = X; x^2 + y^2 )
f (generic function with 1 method)

julia> ForwardDiff.hessian(f, SVector(0..0, 0..0))
2×2 SArray{Tuple{2,2},Interval{Float64},2,4} with indices SOneTo(2)×SOneTo(2):
 [2, 2]  [0, 0]
 [0, 0]  [2, 2]

(v1.3) pkg> st ForwardDiff
    Status `~/.julia/environments/v1.3/Project.toml`
  [f6369f11] ForwardDiff v0.10.3
  [90137ffa] StaticArrays v0.11.0
```

**Comment by dpsanders** [comment]
Thanks that's very useful. Apparently it works correctly with the released version of IntervalArithmetic, but not the branch that I was using, so the problem seems to be there instead. 

Sorry for the noise.
