### ISSUE TITLE
Jacobian of out-of-place function 

### ISSUE THREAD

**Issue by AhmedAlreweny** [JuliaDiff/ForwardDiff.jl#422]
Hello,
I know that ForwardDiff.jl is not able to handle non-julia functions, but I would like to know if it is possible to calculate the Jacobian of an out-of-place function defined in julia as following: 
``` julia
function DerJac(u)

du=0*u


for i=1:Nx

    if i>=3 && i<=Nx-2   # Inner scheme
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2) -(u[i-2]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i+2])/(Δx^4)
    end

    if i==2
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2)-(u[i]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i+2])/(Δx^4)
    end

    if i==Nx-1
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2)-(u[i-2]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i])/(Δx^4)
    end

end

    return du
end 

```

I am trying to calculate the Jacobian at a certain u (for instance u0) as follows: 
``` julia
ForwardDiff.jacobian(DerJac,u)
```
I tried it that way, it didn't throw an error, but gives unreasonable values for the Jac

**Comment by KristofferC** [comment]
What is `Nx`, `Δx`, `c` etc? Why do you say that the jacobian is unreasonable? Please provide enough information so that your issue can be reproduced.

**Comment by AhmedAlreweny** [comment]
that's a finite difference scheme for an PDE. Nx, Δx, c are globally defined variables (mesh and PDE parameters).

**Comment by KristofferC** [comment]
Can you please post the code that is required to run the full example. Also, have you compared the solution vs e.g. finite differences?

**Comment by AhmedAlreweny** [comment]
I created a dummy test-case here 
``` julia

Nx= 20
c=0
Δx=0.1
U= rand(Nx,50)
u0=U[:,1]

function DerJac(u)
du=0*u
for i=1:Nx
    if i>=3 && i<=Nx-2   # Inner scheme
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2) -(u[i-2]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i+2])/(Δx^4)
    end
    if i==2
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2)-(u[i]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i+2])/(Δx^4)
    end
    if i==Nx-1
        du[i]=-(u[i+1]^2-u[i-1]^2)/(4*Δx)-c*(u[i+1]-u[i-1])/(2*Δx)-(u[i+1]-2*u[i]+u[i-1])/(Δx^2)-(u[i-2]-4*u[i-1]+6*u[i]-4*u[i+1]+u[i])/(Δx^4)
    end
end
    return du
end 


Jac_test1=ForwardDiff.jacobian(DerJac,u0)
Jac_test2=ForwardDiff.jacobian(DerJac,U[:,5])
Jac_test3=ForwardDiff.jacobian(DerJac,U[:,8])


```
You can see that the three values of the Jac are almost the same although the U matrix id randomly generated!

**Comment by KristofferC** [comment]
Finite differences (https://github.com/JuliaDiff/FiniteDifferences.jl) gives the same result as ForwardDiff:

```jl
julia> a_jac = ForwardDiff.jacobian(DerJac,U[:,8])
20×20 Array{Float64,2}:
      0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0  …       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
  39903.5  -69800.0   39896.8  -10000.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
 -10000.0   39901.0  -59800.0   39897.3  -10000.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0  -10000.0   39903.2  -59800.0   39897.9  -10000.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0  -10000.0   39902.7  -59800.0   39895.2  -10000.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0  -10000.0   39902.1  -59800.0   39899.6  -10000.0  …      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -59800.0   39896.8         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39900.4  -59800.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39903.2         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39897.2  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39902.8  -59800.0   39896.2  -10000.0      -0.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -10000.0   39900.2  -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …      -0.0  -10000.0   39903.8  -59800.0   39897.7  -10000.0      -0.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0  -10000.0   39900.2  -59800.0   39895.2  -10000.0      -0.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0  -10000.0   39902.3  -59800.0   39895.1  -10000.0
     -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -69800.0   39898.1
      0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0

julia> finite_diff_jac = FiniteDifferences.jacobian(central_fdm(5, 1), DerJac, U[:,8])[1]
20×20 Array{Float64,2}:
      0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
  39903.5          -69800.0           39896.8          -10000.0                  0.0               0.0               0.0               0.0
 -10000.0           39901.0          -59800.0           39897.3                  1.82696e-10       1.82696e-10       1.82696e-10       1.82696e-10
      4.50457e-12  -10000.0           39903.2          -59800.0                  4.50457e-12       4.50457e-12       4.50457e-12       4.50457e-12
     -5.9843e-11       -5.9843e-11   -10000.0           39902.7                 -5.9843e-11       -5.9843e-11       -5.9843e-11       -5.9843e-11
      1.68563e-10       1.68563e-10       1.68563e-10  -10000.0          …       1.68563e-10       1.68563e-10       1.68563e-10       1.68563e-10
     -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11         -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11
     -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10         -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10
     -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11         -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11
      4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11          4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11
      0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
     -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11         -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11
      0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
      0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
      0.0               0.0               0.0               0.0             -10000.0               0.0               0.0               0.0
      0.0               0.0               0.0               0.0          …   39897.7          -10000.0               0.0               0.0
     -1.7053e-12       -1.7053e-12       -1.7053e-12       -1.7053e-12      -59800.0           39895.2          -10000.0              -1.7053e-12
     -1.06338e-11      -1.06338e-11      -1.06338e-11      -1.06338e-11      39902.3          -59800.0           39895.1          -10000.0
     -2.01494e-10      -2.01494e-10      -2.01494e-10      -2.01494e-10     -10000.0           39904.8          -69800.0           39898.1
      0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0

julia> ad_jac ≈ finite_diff_jac
true
```

> You can see that the three values of the Jac are almost the same although the U matrix id randomly generated!

Is not really a good argument. You could compute the analytical derivative and compare if comparing AD and finite differences doesn't convince you.

**Comment by AhmedAlreweny** [comment]
> Finite differences (https://github.com/JuliaDiff/FiniteDifferences.jl) gives the same result as ForwardDiff:
> 
> ```julia
> julia> a_jac = ForwardDiff.jacobian(DerJac,U[:,8])
> 20×20 Array{Float64,2}:
>       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0  …       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
>   39903.5  -69800.0   39896.8  -10000.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>  -10000.0   39901.0  -59800.0   39897.3  -10000.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0  -10000.0   39903.2  -59800.0   39897.9  -10000.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0  -10000.0   39902.7  -59800.0   39895.2  -10000.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0  -10000.0   39902.1  -59800.0   39899.6  -10000.0  …      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -59800.0   39896.8         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39900.4  -59800.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39903.2         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39897.2  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39902.8  -59800.0   39896.2  -10000.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -10000.0   39900.2  -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …      -0.0  -10000.0   39903.8  -59800.0   39897.7  -10000.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0  -10000.0   39900.2  -59800.0   39895.2  -10000.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0  -10000.0   39902.3  -59800.0   39895.1  -10000.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -69800.0   39898.1
>       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
> 
> julia> using FiniteDifferences
> 
> julia> finite_diff_jac = FiniteDifferences.jacobian(central_fdm(5, 1), DerJac, U[:,8])[1]
> 20×20 Array{Float64,2}:
>       0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
>   39903.5          -69800.0           39896.8          -10000.0                  0.0               0.0               0.0               0.0
>  -10000.0           39901.0          -59800.0           39897.3                  1.82696e-10       1.82696e-10       1.82696e-10       1.82696e-10
>       4.50457e-12  -10000.0           39903.2          -59800.0                  4.50457e-12       4.50457e-12       4.50457e-12       4.50457e-12
>      -5.9843e-11       -5.9843e-11   -10000.0           39902.7                 -5.9843e-11       -5.9843e-11       -5.9843e-11       -5.9843e-11
>       1.68563e-10       1.68563e-10       1.68563e-10  -10000.0          …       1.68563e-10       1.68563e-10       1.68563e-10       1.68563e-10
>      -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11         -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11
>      -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10         -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10
>      -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11         -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11
>       4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11          4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11
>       0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
>      -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11         -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0             -10000.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0          …   39897.7          -10000.0               0.0               0.0
>      -1.7053e-12       -1.7053e-12       -1.7053e-12       -1.7053e-12      -59800.0           39895.2          -10000.0              -1.7053e-12
>      -1.06338e-11      -1.06338e-11      -1.06338e-11      -1.06338e-11      39902.3          -59800.0           39895.1          -10000.0
>      -2.01494e-10      -2.01494e-10      -2.01494e-10      -2.01494e-10     -10000.0           39904.8          -69800.0           39898.1
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
> 
> julia> ad_jac ≈ finite_diff_jac
> true
> ```
> 
> > You can see that the three values of the Jac are almost the same although the U matrix id randomly generated!
> 
> Is not really a good argument. You could compute the analytical derivative and compare if comparing AD and finite differences doesn't convince you.

**Comment by AhmedAlreweny** [comment]
> Finite differences (https://github.com/JuliaDiff/FiniteDifferences.jl) gives the same result as ForwardDiff:
> 
> ```julia
> julia> a_jac = ForwardDiff.jacobian(DerJac,U[:,8])
> 20×20 Array{Float64,2}:
>       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0  …       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
>   39903.5  -69800.0   39896.8  -10000.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>  -10000.0   39901.0  -59800.0   39897.3  -10000.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0  -10000.0   39903.2  -59800.0   39897.9  -10000.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0  -10000.0   39902.7  -59800.0   39895.2  -10000.0      -0.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0  -10000.0   39902.1  -59800.0   39899.6  -10000.0  …      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -59800.0   39896.8         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39900.4  -59800.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0   39903.2         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  -10000.0         -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39897.2  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      39902.8  -59800.0   39896.2  -10000.0      -0.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0     -10000.0   39900.2  -59800.0   39899.8  -10000.0      -0.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0  …      -0.0  -10000.0   39903.8  -59800.0   39897.7  -10000.0      -0.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0  -10000.0   39900.2  -59800.0   39895.2  -10000.0      -0.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0  -10000.0   39902.3  -59800.0   39895.1  -10000.0
>      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0      -0.0         -0.0      -0.0      -0.0      -0.0  -10000.0   39904.8  -69800.0   39898.1
>       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0          0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
> 
> julia> using FiniteDifferences
> 
> julia> finite_diff_jac = FiniteDifferences.jacobian(central_fdm(5, 1), DerJac, U[:,8])[1]
> 20×20 Array{Float64,2}:
>       0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
>   39903.5          -69800.0           39896.8          -10000.0                  0.0               0.0               0.0               0.0
>  -10000.0           39901.0          -59800.0           39897.3                  1.82696e-10       1.82696e-10       1.82696e-10       1.82696e-10
>       4.50457e-12  -10000.0           39903.2          -59800.0                  4.50457e-12       4.50457e-12       4.50457e-12       4.50457e-12
>      -5.9843e-11       -5.9843e-11   -10000.0           39902.7                 -5.9843e-11       -5.9843e-11       -5.9843e-11       -5.9843e-11
>       1.68563e-10       1.68563e-10       1.68563e-10  -10000.0          …       1.68563e-10       1.68563e-10       1.68563e-10       1.68563e-10
>      -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11         -7.32573e-11      -7.32573e-11      -7.32573e-11      -7.32573e-11
>      -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10         -1.38007e-10      -1.38007e-10      -1.38007e-10      -1.38007e-10
>      -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11         -1.83067e-11      -1.83067e-11      -1.83067e-11      -1.83067e-11
>       4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11          4.83182e-11       4.83182e-11       4.83182e-11       4.83182e-11
>       0.0               0.0               0.0               0.0          …       0.0               0.0               0.0               0.0
>      -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11         -7.65987e-11      -7.65987e-11      -7.65987e-11      -7.65987e-11
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0             -10000.0               0.0               0.0               0.0
>       0.0               0.0               0.0               0.0          …   39897.7          -10000.0               0.0               0.0
>      -1.7053e-12       -1.7053e-12       -1.7053e-12       -1.7053e-12      -59800.0           39895.2          -10000.0              -1.7053e-12
>      -1.06338e-11      -1.06338e-11      -1.06338e-11      -1.06338e-11      39902.3          -59800.0           39895.1          -10000.0
>      -2.01494e-10      -2.01494e-10      -2.01494e-10      -2.01494e-10     -10000.0           39904.8          -69800.0           39898.1
>       0.0               0.0               0.0               0.0                  0.0               0.0               0.0               0.0
> 
> julia> ad_jac ≈ finite_diff_jac
> true
> ```
> 
> > You can see that the three values of the Jac are almost the same although the U matrix id randomly generated!
> 
> Is not really a good argument. You could compute the analytical derivative and compare if comparing AD and finite differences doesn't convince you.

It is not that I am not convinced. I was wondering whether it is ok to use such a function or not. That was my original questions.

**Comment by KristofferC** [comment]
Yes, it is fine.

**Comment by briochemc** [comment]
@AhmedAlreweny FWIW I think the values of your derivative were almost the same with varying u because your function is close to linear with your choice of Δx and c

**Comment by AhmedAlreweny** [comment]
> @AhmedAlreweny FWIW I think the values of your derivative were almost the same with varying u because your function is close to linear with your choice of Δx and c

This equation represents a chaotic behavior. The square of the convection term is making this equation not only nonlinear, but also chaotic (for a certain domain length).
