### ISSUE TITLE
Update DiffRules dependency to 1.0.0

### ISSUE THREAD

**Issue by homocomputeris** [JuliaDiff/ForwardDiff.jl#431]
It seems that ForwardDiff still pulls DiffRules 0.1.0:
```
pkg> update
↓ DiffRules v1.0.0 ⇒ v0.1.0
```

**Comment by fredrikekre** [comment]
Probably some other package. In a clean environment:
```
$ pkg --project=$(mktemp -d) add ForwardDiff
  Updating `/tmp/tmp.flf5Sg22QU/Project.toml`
  [f6369f11] + ForwardDiff v0.10.8
  Updating `/tmp/tmp.flf5Sg22QU/Manifest.toml`
  [b552c78f] + DiffRules v1.0.0
  [f6369f11] + ForwardDiff v0.10.8
```

**Comment by homocomputeris** [comment]
Sorry, it was a glitch.
ForwardDiff is the only package that depends on DiffRules in my environment. It oscillated between 0.1 and 1.0 with every update until I cleaned the manifest.

**Comment by homocomputeris** [comment]
Well, something strange still happens:
```
pkg> update
  [2b5f629d] ↑ DiffEqBase v6.9.3 ⇒ v6.9.4
  [b552c78f] ↓ DiffRules v1.0.0 ⇒ v0.1.0
```
How can I get info on which packages depend on DiffRules?

**Comment by ChrisRackauckas** [comment]
When in doubt, check Zygote: https://github.com/FluxML/Zygote.jl/pull/433
