### ISSUE TITLE
Jacobian of a multi-inputs function

### ISSUE THREAD

**Issue by AhmedAlreweny** [JuliaDiff/ForwardDiff.jl#445]
Hello, 
I have a function which represents the mapping F(x,p), where x is a vector and p is a scalar parameter. 
The function (mapping) output is a vector. I would like to compute the the jacobian (in this case the directional derivative as I have a scalar parameter p) of the function F wrt the parameter p. How can I go around implementing that. I am using  
``` 
global n
n = x  #vector
 FiniteDifferences.jacobian(central_fdm(3, 1), F, p)[1]
```
to pass the x vector to the function F, which is not ideal. Is there a way to pass the value of x while taking the derivative wrt to p other than the global variables?

**Comment by andreasnoack** [comment]
Hello Admed

Please use discourse.julialang.org for questions.
