### ISSUE TITLE
minor: link to upgrade guide on main README.md is broken, needs updating

### ISSUE THREAD

**Issue by carlosbrody** [JuliaDiff/ForwardDiff.jl#454]
The link to the upgrade guide found in https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/README.md is broken, it produces a "404: File not Found" error. 

The trailing ".html" in the link should be removed

**Comment by devmotion** [comment]
The issue was fixed in https://github.com/JuliaDiff/ForwardDiff.jl/pull/470.
