### ISSUE TITLE
Derivative of `atan2` function

### ISSUE THREAD

**Issue by dbeach24** [JuliaDiff/ForwardDiff.jl#46]
ForwardDiff does not appear to support the `atan2` function:

```julia
using ForwardDiff

function angle(xin)
    x, y = xin
    atan2(y, x)
end

angleJ = jacobian(angle)

angleJ([1.0, 2.0]) # exception!
```

I don't know enough about how to program for the dual number implementation used by ForwardDiff.  ~~However, I believe the derivative at all points is the same as the derivative of `arctan(y/x)`, i.e. `1 / (1 + (y/x)^2)`.~~  CORRECTION: We should be using the partial derivatives of this function w.r.t. to x and y (see below).

**Comment by jrevels** [comment]
Luckily, one doesn't need to know about the inner workings of ForwardDiff in order to support new functions! The only thing that needs to be done to support a new univariate function is to add its derivative rule to Calculus.jl [here](https://github.com/johnmyleswhite/Calculus.jl/blob/master/src/differentiate.jl#L115) (this is something that will get covered in the dev docs as I implement them this week).

Feel free to open an issue in Calculus.jl to support this function, or better yet, submit a PR there that describes the rule.

**Comment by dbeach24** [comment]
`atan2(y, x)` is a two argument function.  While I can believe that this is not a ForwardDiff issue, per se, I can't see how it would go into the table called `symbolic_derivative_1arg_list`.

**Comment by jrevels** [comment]
Oops, I read over your description too quickly and made a poor assumption. My bad.

**Comment by dbeach24** [comment]
Just read further down in `Calculus.jl` and found this gem:

```julia
### Other functions from julia/base/math.jl we might want to define
### derivatives for. Some have two arguments.

## atan2
## hypot
## beta, lbeta, eta, zeta, digamma
```

I suppose someone can and should be added to calculus to support these derivatives (perhaps me), but I can't see how Duals/ForwardDiff would know how to leverage this addition without some more formal infrastructure.  Am I missing something here?

**Comment by KristofferC** [comment]
If I understand correctly, `ForwardDiff.jl` calls `Calculus.jl` to compute all the derivatives for it, to generate the overloaded function. See: https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/GradientNumber.jl#L172

**Comment by jrevels** [comment]
@dbeach24 Your `angle` function takes a `Vector` and returns a `Number`:

```julia
function angle(xin)
    x, y = xin
    atan2(y, x)
end
```

The reason for the error is that you should've used ForwardDiff's `gradient` function instead of the `jacobian` function:

```julia
julia> angleg = gradient(angle);

julia> angleg([1.0, 2.0])
2-element Array{Float64,1}:
 -0.4
  0.2
```

Is that the correct result?

**Comment by jrevels** [comment]
That doesn't detract from the issue of supporting `atan2`, though. 

This should still work, but doesn't:

```julia
julia> function angle(xin)
           x, y = xin
           [atan2(y, x)]
       end
angle (generic function with 1 method)

julia> angleJ = jacobian(angle)
j (generic function with 1 method)

julia> angleJ([1.0, 2.0])
ERROR: MethodError: `atan2` has no method matching atan2(::ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}, ::ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}})
Closest candidates are:
  atan2{T1<:Number,T2<:Number}(::T1<:Number, ::AbstractArray{T2<:Number,N})
  atan2{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::T2<:Number)
 in angle at none:3
 in _calc_jacobian at /Users/jarrettrevels/.julia/ForwardDiff/src/fad_api/jacobian.jl:86
 in j at /Users/jarrettrevels/.julia/ForwardDiff/src/fad_api/jacobian.jl:54
```

**Comment by jrevels** [comment]
> If I understand correctly, ForwardDiff.jl calls Calculus.jl to compute all the derivatives for it, to generate the overloaded function.

To clarify, we use Calculus.jl to automatically construct the overloaded function definitions because the algebra of dual numbers allows us to derive the form for general univariate functions on our dual number types. It's quite nice, especially for the [HessianNumber](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/HessianNumber.jl#L92) and [TensorNumber](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/TensorNumber.jl#L92) cases.

**Comment by jrevels** [comment]
**I found out the reason `atan2` why doesn't work**: [it's not a native Julia function](https://github.com/JuliaLang/julia/blob/master/base/math.jl#L169). If it was, it'd likely work without any extra effort on our part.

@mlubin How should we handle this case, and others like it? The current `atan2` methods are restricted to `Float64`, so we could define a native Julia version for `Base.atan2(y::Number, x::Number)`. If we simply provide this method, ForwardDiff should work, and the `Float64` version will still get called correctly. I'd just be worried about the performance of my potential native Julia implementation.

**Comment by jrevels** [comment]
wait, how the hell does this work then:

```julia
julia> function angle(xin)
           x, y = xin
           atan2(y, x)
       end
angle (generic function with 1 method)

julia> angleg = gradient(angle);

julia> angleg([1.0, 2.0])
2-element Array{Float64,1}:
 -0.4
  0.2
```

I'm screwing something up here...

**Comment by jrevels** [comment]
ARGH! I was accidentally using Calculus's version of `gradient`, I forgot to qualify the full name:

```julia
julia> angleg = ForwardDiff.gradient(angle);

julia> angleg([1.0, 2.0])
ERROR: MethodError: `atan2` has no method matching atan2(::ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}, ::ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}})
Closest candidates are:
  atan2{T1<:Number,T2<:Number}(::T1<:Number, ::AbstractArray{T2<:Number,N})
  atan2{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::T2<:Number)
 in angle at none:3
 in _calc_gradient at /Users/jarrettrevels/.julia/ForwardDiff/src/fad_api/gradient.jl:86
 in g at /Users/jarrettrevels/.julia/ForwardDiff/src/fad_api/gradient.jl:54
```

**Comment by dbeach24** [comment]
@jrevels It is not at all surprising to me that `atan2` is not implemented in Julia.  As with other trig functions, you really want this to be implemented as close to the metal as possible.  A naïve implementation might incur extra unnecessary branching which a hardware implementation could altogether avoid.

Also, regarding you comment about it supporting only `Float64`.  (Did I misunderstand?)  `atan2` appears to support all the normal float types:

```julia
julia> methods(atan2)
# 9 methods for generic function "atan2":
atan2(y::Float64, x::Float64) at math.jl:174
atan2(y::Float32, x::Float32) at math.jl:175
atan2(a::Float16, b::Float16) at float16.jl:157
atan2(y::BigFloat, x::BigFloat) at mpfr.jl:634
atan2{T<:AbstractFloat}(y::T<:AbstractFloat, x::T<:AbstractFloat) at math.jl:170
atan2(y::Real, x::Real) at math.jl:169
atan2{T1<:Number,T2<:Number}(::T1<:Number, ::AbstractArray{T2<:Number,N}) at operators.jl:385
atan2{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::T2<:Number) at operators.jl:387
atan2{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::AbstractArray{T2<:Number,N}) at operators.jl:391
```

**Comment by mlubin** [comment]
Are there any other two-argument functions that we'd like to support? Calculus doesn't recognize any besides a special case for bessel functions. Trying to decide if we should special-case it here or add new machinery to Calculus.

**Comment by jrevels** [comment]
> A naïve implementation might incur extra unnecessary branching which a hardware implementation could altogether avoid.

Yeah, that's what I figured. What I suggested (though I guess wasn't very clear about) was defining:

```julia
Base.atan2(y::Number, x::Number) = atan(y/x)
```

I guess it'd be better to be more restrictive:

```julia
Base.atan2(y::ForwardDiffNumber, x::ForwardDiffNumber) = atan(y/x)
```

The reason I'm nervous about this is supporting it could trick folks into thinking we actually *do* support some optimized version of `atan2`, when in reality it would just be a shim for the sake of feature-completeness.

I guess the best argument is that ForwardDiff is supposed to be able to differentiate black-box functions, so it shouldn't fail for little cases like these.

> Also, regarding you comment about it supporting only Float64

You're right, I slipped up with my word choice there.

**Comment by mlubin** [comment]
I don't see any issue at all with defining
```
Base.atan2(y::ForwardDiffNumber, x::ForwardDiffNumber) = atan(y/x)
```
(plus promotion when either arg is a plain number) as long as it gives the right answer. Going a little slow is better than crashing. Is the derivative supposed to be defined when ``x = 0``?

**Comment by jrevels** [comment]
> Base.atan2(y::Number, x::Number) = atan(y/x)
> I guess it'd be better to be more restrictive:
> 
> Base.atan2(y::ForwardDiffNumber, x::ForwardDiffNumber) = atan(y/x)

Wait - just doing a little reading. I assumed `atan2` was just a more performant alias for `atan(y/x)`. The [conveniently existent wikipedia page](https://en.wikipedia.org/wiki/Atan2) for the function defines it piecewise (where the added things are all constants). So you believe a Julia implementation would necessarily involve branching due to the piecewise nature of `atan2`, @dbeach24?

**Comment by jrevels** [comment]
Like @dbeach24 pointed out, the derivatives should work out the same, so we could *really* special case it and define it for all the `ForwardDiffNumber` types (the definition looking exactly like `atan` except `x`→`y/x` and the value is calculated using `atan2`). 

> Trying to decide if we should special-case it here or add new machinery to Calculus.

It would be nice for Calculus to have regardless. My lofty dream is to define an algebraic form for multivariate functions on the dual number types in the same way that I did for the univariate functions, so we could start supporting functions like these automatically given a differentiation rule a la Calculus. I'm not even sure whether that's generally possible or not, though, and it's probably not easy...

The aformentioned special-case implementation for all the `ForwardDiffNumber` types would at least be enough to close this issue, and if we come up with a list of more functions like these (e.g. elementary functions we want to support that aren't native Julia functions), we can focus on generalizing later.

**Comment by jrevels** [comment]
> Is the derivative supposed to be defined when x = 0?

[I think it's  0](https://en.wikipedia.org/wiki/Atan2#Definition_and_computation). Thus, I was wrong again above - `1 / (1 + (y/x)^2)` wouldn't be the correct form of the derivative at `x=0`, so special-casing `atan2` would be, I guess, more complicated than I thought...

**Comment by jrevels** [comment]
Oh hey, [look what's a couple sections down on that very page](https://en.wikipedia.org/wiki/Atan2#Derivative).

**Comment by jrevels** [comment]
> Thus, I was wrong again above - 1 / (1 + (y/x)^2) wouldn't be the correct form of the derivative at x=0, so special-casing atan2 would be, I guess, more complicated than I thought...

Just tried this out, I didn't realized Julia did this:

```julia
julia> 1/Inf
0.0
```

So I guess that I could special-case fairly easily after all.

**Comment by dbeach24** [comment]
Looking at the wikipedia article, it is correct that since this is a 2-argument function, what we really need are the partials with respect to x and y.  I would use those formulae, and please ignore what I wrote earlier.

https://en.wikipedia.org/wiki/Atan2#Derivative

**Comment by dbeach24** [comment]
@mlubin Regarding the support of functions with >= 2 args in `Calculus.jl`, I wonder if the following table would suffice:

```julia
symbolic_derivative_2arg_list = [
    # FORMAT:
    # (:func_name, :partial_wrt_first_arg, :partial_wrt_second_arg),
    # for atan2, this would be something like:
    (:atan2, :(b / (a^2 + b^2)), :(-a / (a^2 + b^2)),
]
```

Note that here, I have assumed that the arguments are labelled a and b (in that order).  This naming choice is a bit unnatural for `atan2`, but is a more general naming scheme than using y and x...

**Comment by jrevels** [comment]
> Looking at the wikipedia article, it is correct that since this is a 2-argument function, what we really need are the partials with respect to x and y. I would use those formulae, and please ignore what I wrote earlier.

Actually, unless I'm mistaken, what you wrote earlier *is* the expression we need to define the kind of total derivative required for dual numbers to work properly. I'll probably submit a PR to add this special-case this week, and it might make more sense then.

**Comment by jrevels** [comment]
(The expression I'm talking about could be derived from the partials, as they do for theta in the article, but the derivations can be messy/tedious for higher order epsilon components. The similarity of `atan2(y, x)` --> `atan(y/x)` at all differentiable points gives us a shortcut that makes life easier.)
