### ISSUE TITLE
extract_jacobian calls generic function in generated function

### ISSUE THREAD

**Issue by andreasnoack** [JuliaDiff/ForwardDiff.jl#468]
This makes the behavior depend on the load order of packages which is unfortunate. The problematic definition is

https://github.com/JuliaDiff/ForwardDiff.jl/blob/c4487d5620983581f6a63284cca3599b8dacf203/src/jacobian.jl#L97-L105

**Comment by KristofferC** [comment]
Could just move in `V` inside the `quote` right?

**Comment by andreasnoack** [comment]
I would think so.
