### ISSUE TITLE
a few simple examples would be great

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaDiff/ForwardDiff.jl#48]
Assuming the source code would be relatively brief,
it would be helpful to see a couple of simple examples in full:
e.g. how to use it with sin(x::Real) x in -Pi/2..Pi/2
and perhaps, f(z::Complex) z in whatever range looks good

**Comment by jrevels** [comment]
The [docs](http://www.juliadiff.org/ForwardDiff.jl/index.html) are littered with examples, there's even one in the package's README.

> f(z::Complex)

As it says in the docs, ForwardDiff.jl doesn't yet support `Complex`  numbers

**Comment by jrevels** [comment]
Though I suppose it makes sense to have a brief example for each section [here](http://www.juliadiff.org/ForwardDiff.jl/perf_diff.html)

**Comment by JeffreySarnoff** [comment]
I did look through the docs first.  It may be that we are using "example"
in different senses, or it may be that I simply missed them.  My request
was for a few very simple fully self-contained examples to use as
boilerplate while getting familiar with your estimable work.

const myrange = (-pi/2.0, pi/2.0)
function myfunc(x) = sin(x)

?sample myfunc over my range to create a vector of values
?hand it off to yourfunc to do its stuff
?examine/plot the result

**Comment by JeffreySarnoff** [comment]
​I would not ask if I did not know how useful your work is.​

**Comment by mlubin** [comment]
@JeffreySarnoff, there's no sampling of values involved in ForwardDiff.
```
using ForwardDiff
myfunc(x) = sin(x)
derivative(myfunc, 1.0)
```
will return a value equal to ``cos(1.0)``. That's basically all there is to it.

**Comment by JeffreySarnoff** [comment]
thanks
