### ISSUE TITLE
Having a jvp function for jacobian vector product

### ISSUE THREAD

**Issue by theogf** [JuliaDiff/ForwardDiff.jl#487]
Following a discussion on Slack we realized there is no Jacobian-Vector product function in ForwardDiff.jl.
The idea would be to have a function `jvp(foo, x, v) = jacobian(foo, x) * v`.
A solution proposed is to rewrite it as a derivative: 
```
function jvp(foo, x, v)
  derivative(0) do t
    foo(x .+ t .* v)
  end
end
```
Edit : Same issue as #319

**Comment by KristofferC** [comment]
Close as dup
