### ISSUE TITLE
AD Hessian is inaccurate for only one entry

### ISSUE THREAD

**Issue by tholdem** [JuliaDiff/ForwardDiff.jl#488]
This is the function I encountered problem with Hessian.

```
f(x,y)  = 1/2*(x^2 - y^2)
sigma2  = .2
g(x,y)  = exp(-(x^2+y^2)/sigma2)
h(x,y)  = f(x,y)*g(x,y)
h_x(x,y)  = x*g(x,y) - 1/sigma2*(x^2-y^2)*x*g(x,y)
h_y(x,y)  = -y*g(x,y) - 1/sigma2*(x^2-y^2)*y*g(x,y)


h_xx(x,y) = 2*x^4 + sigma2*(y^2+sigma2)-x^2*(2*y^2+5*sigma2)
h_xy(x,y) = 2*x*y*(x^2-y^2)
h_yx(x,y) = h_xy(x,y)
h_yy(x,y) = -2*y^4+sigma2*y^2*sigma2-sigma2^2+x^2*( 2*y^2-sigma2)
hess(x,y) = g(x,y)/(sigma2^2)*[ h_xx(x,y) h_xy(x,y); h_yx(x,y) h_yy(x,y)]

F(xvec) =  h(xvec[1],xvec[2])
Grad(xvec) = [h_x( xvec[1], xvec[2] ); h_y( xvec[1], xvec[2] ) ]
Hess(xvec) = hess( xvec[1], xvec[2] )

x0=[0.419;0.887]
ForwardDiff.hessian(F,x0)
Hess(x0)
```
and you can see that they agree on all entries except for the last one:
![image](https://user-images.githubusercontent.com/62815109/102042755-922c5880-3dca-11eb-8f96-a367ef979c01.png)

This is not an isolated case. A lot of different values of x0 gave the same problem. So does Zygote's AD Hessian. I'd love to hear your thoughts on why this is happening?

**Comment by tomaklutfu** [comment]
It seems `h_xx(x,y)` or `h_yy(x,y)` is wrong in a first glance because they should just exchange x and y but it is not the case.

**Comment by KristofferC** [comment]
Did you check your analytical result with e.g. Finite difference?

**Comment by tholdem** [comment]
This is so embarrassing, I assumed that the Hessian given to me was correct but there was indeed a mistake. Everything is fine now! I apologize for this mistake.
