### ISSUE TITLE
Question: Algebra

### ISSUE THREAD

**Issue by EricForgy** [JuliaDiff/ForwardDiff.jl#49]
This is cool stuff! I have a few questions...

If I understand, GradientNumbers share a single epsilon (e) so the algebra of GradientNumbers is completely determined by that of the reals, linearity, plus e^2 = 0, i.e.

(a+b*e)*(c+d*e) = a*c + (a*d+b*c)*e

There is no concept of distinct epsilons e1 and e2 for GradientNumbers. Is that correct?

HessianNumbers, on the other hand have 2 distinct epsilons e1 and e2. The documentation (in the source code) states that 

e1 != 0, e2 != 0

e1^2 = e2^2 = (e1*e2)^2 = 0

But what is the product e1*e2? Do you assume e1 and e2 commute?

Consider the sum e1+e2. Is this an epsilon? If e1+e2 is an epsilon and e1 and e2 commute, then e1*e2 = 0, which would not be very interesting. I guess the epsilons are not closed under addition (too bad!).

Similarly, for TensorNumbers, do you assume the 3 epsilons commute? It seems so.

It would be interesting to consider non-commuting epsilons closed under addition such that

(e1+e2)^2 = e1*e2 + e2*e1 = 0 => e1*e2 = -e2*e1.

This would allow you to use AD ideas for (Kaehler) differential forms and more general abstract differential algebras.

More generally, I think it is interesting to consider differentials of epsilons, e.g.

df = @f_i de^i (Einstein summation)

I did some work along these lines in grad school (13+ years ago... ouch. Getting old :))

It gets fun if you let 0-forms (functions) and 1-forms (differentials) not commute, i.e.

f(x) de = de f(x+e)

This has a nice geometric interpretation. We can consider e to be an infinitesimal curve and multiplying the function on the left of de evaluates at the beginning of the curve and multiplying on the right evaluates at the end of the curve.

This is nice because

[de,f] = f'(x) de

i.e. the derivative may be expressed as a commutator which automatically satisfies the product rule.

[de,fg] = [de,f] g + f [de,g]

(but the order matters above :))

**Comment by jrevels** [comment]
Hopefully #51 will at least address a little bit of this, but I'll try to answer what I can:

> If I understand, GradientNumbers share a single epsilon (e) so the algebra of GradientNumbers is completely determined by that of the reals, linearity, plus e^2 = 0, i.e.
> 
> (a+be)(c+de) = ac + (ad+bc)*e
> 
> There is no concept of distinct epsilons e1 and e2 for GradientNumbers. Is that correct?

It depends on what you mean, but if you're referring to "distinct epsilons" in the sense of hyper-dual numbers, I think this is basically correct. One way to think of it is that a `GradientNumber{N}` stores an ensemble of `N` dual numbers, but they all share the same real component.

> But what is the product e1*e2? Do you assume e1 and e2 commute?

Yes, e1 * e2 = e2 * e1.

> Consider the sum e1+e2. Is this an epsilon?

Hyper-dual numbers are closed under addition, but I'm not sure whether the epsilon components themselves are closed under addition. One way that I've seen epsilons described are as infinitesimal perturbation vectors. If that's true, and the space of epsilons can be thought of as a vector space, then I suppose they must be closed under addition, and that e1+e2 would be another vector in the space. I'm not sure how that interpretation holds up to rigor; my abstract algebra background is not nearly as strong as I'd like it be.

The "practical" algebra of hyper-dual numbers is developed in [this paper](https://adl.stanford.edu/hyperdual/Fike_AIAA-2011-886.pdf). 

> Similarly, for TensorNumbers, do you assume the 3 epsilons commute? It seems so.

Yes.

> It would be interesting to consider non-commuting epsilons closed under addition such that
> 
> (e1+e2)^2 = e1e2 + e2e1 = 0 => e1e2 = -e2e1.
> 
> This would allow you to use AD ideas for (Kaehler) differential forms and more general abstract differential algebras.
>...
> [de,fg] = [de,f] g + f [de,g]
> 
> (but the order matters above :))

Do you have any papers you could link? I'm always interested in learning more about perturbation theory/epsilon algebras.

Anyway, I'm going to close this issue, but feel free to continue to discuss.
