### ISSUE TITLE
float(::Dual) disagrees with Base

### ISSUE THREAD

**Issue by mcabbott** [JuliaDiff/ForwardDiff.jl#492]
I was surprised by this:
```
using ForwardDiff: Dual, value
x1 = Dual.(1:4, 2:5, 3:6)
value.(float.(x1)) # Vector{Float16}
float.(value.(x1)) # Vector{Float64}
```
While one could argue that Julia should have different promotion / widening rules, it seems hard to argue that Dual types should disagree. This example caught me when trying to wrap a function which only accepts Float32 & Float64, as seems fairly common for C libraries. 

Edit -- xref #419, about AbstractFloat. 

And #362, about Int -> Float16. Example from [here](https://discourse.julialang.org/t/what-functions-might-break-forwarddiff-jl/64694/8) is `ForwardDiff.derivative(first∘sincos, 1) isa Float16`

**Comment by stevengj** [comment]
It seems like this line https://github.com/JuliaDiff/ForwardDiff.jl/blob/6b393f44913946d79ad4eebe000e09e6540cc124/src/dual.jl#L383-L384
should just use `float(V)` rather than `promote_type(V, Float16)`
