### ISSUE TITLE
Function typing restrictions

### ISSUE THREAD

**Issue by swt30** [JuliaDiff/ForwardDiff.jl#50]
So, first, this is a wicked package and I'm a complete convert to this AD thing! 

I was wondering what the rationale is behind the type restrictions on functions. I can make ForwardDiff work excellently most of the time but I'm hitting a snag in one place. I'm doing triangulation and interpolation on unstructured data points, and using the package GeometricalPredicates to test if things are in triangles.  The snag is that GeometricalPredicates has a custom `Point(x::Real, y::Real)` type, and ForwardDiff needs that to be `Point(x::Number, y::Number)` to pass its custom number type through. Given that we're currently limited to differentiating real functions anyway, is there any particular reason for that restriction? Is it to make adding complex differentiation easier later on?

**Comment by swt30** [comment]
A little more investigation reveals that GeometricalPredicates might not work with custom number types anyway, since it explicitly takes advantage of Float64s to do something called floating point filtering. And I guess this package is using something more complicated than real numbers anyway, so it wouldn't be right to pass them to a function that requires actual reals.

**Comment by mlubin** [comment]
The numbers used by ForwardDiff are not real numbers. If we pretended they were, we might break things, though it's not necessarily a bad idea.
Algorithms that take advantage of the explicit representation of floats will definitely be tricky to differentiate, it would likely require a bunch of changes to their code.

**Comment by swt30** [comment]
I found a nice workaround just using multiple dispatch to choose a finite differencing method on the types that don't support automatic differentiation, so it worked out well.
