### ISSUE TITLE
ForwardDiff.jl does not throw an error even when function outputting an array is used to calculate the Hessian

### ISSUE THREAD

**Issue by SarThak191119** [JuliaDiff/ForwardDiff.jl#501]
This might already be a redundant doubt if someone else has asked this but I was trying to use Forward Diff to calculate the Hessian and as the title suggests the documentation is clear that the function has to output a real number. It’s just that the Hessian outputs an array of Dual numbers if the function outputs an array and if the x at which it is evaluated is an array of dimension > 2. I might be missing something and attaching a MWE for reference.
```
using ForwardDiff

f(x)= [sum(x.^2 .+3)]
x0=rand(3,3,2)
H_12=ForwardDiff.hessian(f,x0)
```
I am working on Julia 1.4 and I have the latest version of ForwardDiff(v0.10.12)

**Comment by mcabbott** [comment]
Should be fixed by #489, latest version is v0.10.15:
```
julia> H_12=ForwardDiff.hessian(f,x0)
ERROR: DimensionMismatch("gradient(f, x) expects that f(x) is a real number. Perhaps you meant jacobian(f, x)?")
```
