### ISSUE TITLE
Support structured (banded) Jacobians?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDiff/ForwardDiff.jl#507]
@ChrisRackauckas Have you thought about how one would incorporate structured Jacobians? 

For example, if I have the function
```julia
x -> x[2:end]
```
then the Jacobian would ideally be sparse:
```julia
julia> BandedMatrix(Ones(length(x)-1,length(x)), (-1,1))
3×4 BandedMatrix{Float64} with bandwidths (-1, 1):
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0
```
This would require a fundamental redesign of this package where the Jacobians are stored as matrices. That is, instead of a vector of `Dual`s we would want the fundamental type to be something like:
```julia
struct DualVector{T, Vec<:AbstractVector{T}, Jac<:AbstractMatrix{T}} <: AbstractVector{Dual{T}}
   vector::Vec
   jacobian::Jac
end
Base.getindex(x::DualVector, k::Integer) = Dual(x.vector[k], x.jacobian[k,:])
```
So the current implementation for static arrays based on evaluating a  `SVector{N, Dual{<:Tag, T, M}}` would be replaced by a `DualVector{T,SVector{N,T}, SMatrix{N, N, T, N^2}}`.

This is a major change so probably best done in a separate package named DualVectors.jl at first. But wanted to bounce the idea off people first.

PS The nice thing is would also enable ∞-dimensional auto-differentiation.

**Comment by ChrisRackauckas** [comment]
This is already done in SparseDiffTools.jl

**Comment by ChrisRackauckas** [comment]
Note that the stuff in ArrayInterface.jl makes it so many structured matrices have an analytic solution to the coloring problem when `matrix_colors` is run. If you want ∞-dimensional auto-differentiation you may just need to make sure that you get an appropriate infinite colorvec.

**Comment by dlfivefifty** [comment]
Looking at the code it looks like its solving a different problem of automatically determining sparsity. For my case I should know the sparsity because only certain operations are allowed. E.g., `for i in 2:length(x)-1` will never happen with infinite arrays so instead the equivalent code to your example would be:
```julia
function f(x)
   [0; x] -2x + x[2:end]
end
```
When `x` is infinite, I don't think this code will fit into the SparseDiffTools.jl framework, so perhaps there's still a place for a DualVectors.jl?

I think getting the code above to work should be pretty easy, something like:
```julia
struct DualVectorStyle <: AbstractArrayStyle{1} end
Base.BroadcastStyle(::Type{<:DualVector}) = DualVectorStyle()
vcat(x::Number, y::DualVector) = DualVector([x; y.vector], Eye(length(x)+1)[:,2:end] * y.jacobian)
getindex(y::DualVector, kr::AbstractRange) = Eye(length(y))[kr,:]
Base.broadcasted(::DualVectorStyle, ::typeof(*), x::Number, y::DualVector) = DualVector(x .* y.vector, x .* y.jacobian)
Base.broadcasted(::DualVectorStyle, ::typeof(+), x:: DualVector, y::DualVector) = DualVector(x.vector .+ y.vector, x.jacobian .+ y.jacobian)
```

**Comment by ChrisRackauckas** [comment]
>Looking at the code it looks like its solving a different problem of automatically determining sparsity

It doesn't do that. It requires that you know the sparsity.

**Comment by dlfivefifty** [comment]
PS the in-place, non-allocating version would look like:
```julia
function f!(y, x)
   y .= Vcat(0, x) .- 2 .* x .+ view(x,2:end)
end
```
With a bit of work this can be made as fast as the example code with the for loop.
