### ISSUE TITLE
Support `normalize`

### ISSUE THREAD

**Issue by oschulz** [JuliaDiff/ForwardDiff.jl#521]
We should support `LinearAlgebra.normalize` and  `LinearAlgebra.normalize!`. Unfortunately, the default implementation isn't compatible with duals,  because `LinearAlgebra.__normalize!` requires an `AbstractFloat`:

```
julia> normalize!(ForwardDiff.Dual.(rand(5), rand(5)))
ERROR: MethodError: no method matching __normalize!(::Vector{ForwardDiff.Dual{Nothing, Float64, 1}}, ::ForwardDiff.Dual{Nothing, Float64, 1})
Closest candidates are:
  __normalize!(::AbstractArray, ::AbstractFloat) at [...]/LinearAlgebra/src/generic.jl:1678
```

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/julia/pull/41045

**Comment by oschulz** [comment]
Thanks, @KristofferC !
