### ISSUE TITLE
method conj overwritten in dual.jl

### ISSUE THREAD

**Issue by dehann** [JuliaDiff/ForwardDiff.jl#531]
Good day,

I did not see a prior issue for this:
```julia
using ForwardDiff
WARNING: Method definition conj(ForwardDiff.Dual{T, V, N} where N where V where T) in module ForwardDiff at
/home/dehann/.julia/packages/ForwardDiff/QOqCN/src/dual.jl:201 overwritten at 
/home/dehann/.julia/packages/ForwardDiff/QOqCN/src/dual.jl:381.
  ** incremental compilation may be fatally broken for this module **
```

Think the warning gets suppressed after precompilation during updates.

EDIT, and status, sorry:
```julia
(@v1.6) pkg> st ForwardDiff
      Status `~/.julia/environments/v1.6/Project.toml`
  [f6369f11] ForwardDiff v0.10.18
```

**Comment by felipenoris** [comment]
This is happening after this update: `DiffRules v1.0.2 ⇒ v1.2.1`

**Comment by mcabbott** [comment]
The two rules are 

https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/dual.jl#L381

https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl#L71

I believe they are doing the same thing, and that we should just delete the one here. 

It's weird that you still get 1.2.1, https://github.com/JuliaRegistries/General/pull/40225 was meant to block everything above 1.0.2.
