### ISSUE TITLE
Tag releases regularly

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaDiff/ForwardDiff.jl#540]
Is there a reason tagging is delayed? It's been several months since the last tag, which makes it hard to depend on fixes in PRs.

I tend to tag any PR that has a bump in patch version. Could this be the new policy?

**Comment by fredrikekre** [comment]
I have figured out that the single most effective way to get out a release is to either make a PR that bumps the version number, or simply bump the version number in the bugfix PR itself. That makes it very easy for a maintainer to just press merge and then directly tag.

**Comment by dlfivefifty** [comment]
Which is what I did... so master is v0.10.19 but the last tag is still v0.10.18

**Comment by fredrikekre** [comment]
Ah okay, sorry.

**Comment by KristofferC** [comment]
> Is there a reason tagging is delayed

No one just did it yet. The activity on this repo was very low for quite some time so there isn't really a release "policy". 

Anyway, https://github.com/JuliaRegistries/General/pull/41858
