### ISSUE TITLE
Derivating J2-plasticity yield function

### ISSUE THREAD

**Issue by ovainola** [JuliaDiff/ForwardDiff.jl#55]
Hi,

I was making this example an I noticed something weird which I couldn't figure out. I was working with J2 plasticity model (see link, under Reduced von Mises equation for different stress conditions). When I took gradient from function it only gave NaN vector

https://en.wikipedia.org/wiki/Von_Mises_yield_criterion

Code:
```julia
>> using ForwardDiff
>> function J2(σ)
    e1 = (σ[1] - σ[2])^2
    e2 = (σ[2] - σ[3])^2
    e3 = (σ[3] - σ[1])^2
    e4 = σ[4]^2 
    e5 = σ[5]^2
    e6 = σ[6]^2
    return sqrt(( e1 + e2 + e3 + 6 * (e4 + e5 + e6)) / 2.)
end

>> x= [100.0, 0.0, 0.0, 0.0, 0.0, 0.0]
>> dJ2 = ForwardDiff.gradient(J2)
>> dJ2(x)

[NaN,NaN,NaN,NaN,NaN,NaN]
```

I also tested the typical forward derivate

```julia
>> h = 1e-12
>> numerical_vals = zeros(Float64, 6)
>> for i=1:6
    vals = copy(x)
    vals[i] += h
    numerical_vals[i] = (J2(vals)- J2(x)) / h
end
>> numerical_vals

6-element Array{Float64,1}:
  0.99476
 -0.49738
 -0.49738
  0.0    
  0.0    
  0.0 
```
Background: I just updated into Julia 0.5 dev version so might that have something to do with this?

**Comment by jrevels** [comment]
[Here's the culprit](https://github.com/JuliaDiff/ForwardDiff.jl/commit/11e29a1e7971e3679dc41c2b6a7f31a064668f46#diff-0e4d37f9a919bf1a8c7360e8dd2bd15dL125).

I shouldn't have replaced an exponentiation + subtraction with a division...I'll push a fix soon.

**Comment by jrevels** [comment]
On the latest master, now that this is fixed:

```julia
julia> using ForwardDiff
WARNING: Base.Uint64 is deprecated, use UInt64 instead.
WARNING: Base.Uint64 is deprecated, use UInt64 instead.
WARNING: Base.Uint64 is deprecated, use UInt64 instead.
WARNING: Base.Uint64 is deprecated, use UInt64 instead.

julia> function J2(s)
           e1 = (s[1] - s[2])^2
           e2 = (s[2] - s[3])^2
           e3 = (s[3] - s[1])^2
           e4 = s[4]^2
           e5 = s[5]^2
           e6 = s[6]^2
           return sqrt((e1 + e2 + e3 + 6 * (e4 + e5 + e6)) / 2)
       end
J2 (generic function with 1 method)

julia> x = [100., 0., 0., 0., 0., 0.]
6-element Array{Float64,1}:
 100.0
   0.0
   0.0
   0.0
   0.0
   0.0

julia> ForwardDiff.gradient(J2, x)
6-element Array{Float64,1}:
  1.0
 -0.5
 -0.5
  0.0
  0.0
  0.0
```

Thanks for finding this! Now to get rid of those depwarns...

**Comment by ovainola** [comment]
Thanks for fixing this so fast! I was banging my head with nlsolve for couple of hour since it didn't converge before figuring out the problem was the gradient. Now I can continue with my experiments with nonlinear materials.
