### ISSUE TITLE
Spurious type promotions due to Float64 coefficients in the diff rules

### ISSUE THREAD

**Issue by KristofferC** [JuliaDiff/ForwardDiff.jl#566]
```jl
julia> r = 1.0f0;

julia> sind(r) |> typeof
Float32

julia> d = ForwardDiff.Dual(1.0f0, 2.0f0);

julia> sind(d) |> typeof
ForwardDiff.Dual{Nothing, Float64, 1}
```

This last one should still be in the Float32 domain. All the coefficients in https://github.com/JuliaDiff/DiffRules.jl/blob/master/src/rules.jl#L29 probably need to take on the value type of the input dual.

**Comment by devmotion** [comment]
The problem in this specific rule (and many others in DiffRules) seems to be that the irrational `π / 180` is computed and promoted to `Float64` automatically, without taking into account the other terms. Simply rearranging the terms to `- (π * sind($x)) / 180` would fix this problem. @torfjelde tried to address this problem for multiple rules in https://github.com/JuliaDiff/DiffRules.jl/pull/55.

**Comment by devmotion** [comment]
This issue was fixed in https://github.com/JuliaDiff/DiffRules.jl/pull/55. With DiffRules >= 1.9.1:
```julia
julia> r = 1.0f0;

julia> sind(r) |> typeof
Float32

julia> d = ForwardDiff.Dual(1.0f0, 2.0f0);

julia> sind(d) |> typeof
ForwardDiff.Dual{Nothing, Float32, 1}
```
