### ISSUE TITLE
MethodError: no method matching getrf!(::CuArray{ForwardDiff.Dual{ForwardDiff.Tag{ODEFunction

### ISSUE THREAD

**Issue by ronogue** [JuliaDiff/ForwardDiff.jl#612]
Hi, I'm using Optimization.jl to training a universal differential equation and it uses ForwardDiff.jl under the hood but, I am trying to make use of GPU and configured all parameters and initial condition with Lux.gpu. But, when it start the optimization, I get this error:

```
MethodError: no method matching getrf!(::CuArray{ForwardDiff.Dual{ForwardDiff.Tag{ODEFunction{true, SciMLBase.AutoSpecialize, typeof(nn_dynamics!), UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing}, Float32}, Float32, 11}, 2, CUDA.Mem.DeviceBuffer})
Closest candidates are:
  getrf!(::StridedCuMatrix{Float32}) at ~/.julia/packages/CUDA/DfvRa/lib/cusolver/dense.jl:120
  getrf!(::StridedCuMatrix{Float64}) at ~/.julia/packages/CUDA/DfvRa/lib/cusolver/dense.jl:120
  getrf!(::StridedCuMatrix{ComplexF32}) at ~/.julia/packages/CUDA/DfvRa/lib/cusolver/dense.jl:120
  ...
```

There is something I should be aware about using ForwardDiff.jl with GPU? I tried to search any similar error but none of them helped me.

**Comment by andreasnoack** [comment]
This is not something to be fixed in this package. Please try to ask on Discourse to get some direction on how to proceed with this issue.
