### ISSUE TITLE
Installing ForwardDiff

### ISSUE THREAD

**Issue by econotron** [JuliaDiff/ForwardDiff.jl#68]
I am a new user to ForwardDiff and not super Julia savvy. I tried installing it on a brand new Amazon cloud instance running RHEL 7. This Linux install is clean and up to date; I have installed nothing other than Julia 0.4-dev and dependencies on it. I got Julia from

https://copr.fedoraproject.org/coprs/nalimilan/julia/

Pkg.add("ForwardDiff") works fine.

When I type using ForwardDiff I get the following error:

julia> using ForwardDiff
ERROR: LoadError: syntax: invalid "import" statement
while loading /home/ec2-user/.julia/v0.4/ForwardDiff/src/ForwardDiff.jl, in expression starting on line 25

**Comment by mlubin** [comment]
What version of Julia are you using? See the output of ``versioninfo()``.
Julia 0.4 development releases are not supported, you must be using the Julia 0.4.0 release or later.

**Comment by mlubin** [comment]
@jrevels, should bump ``0.4-`` in REQUIRE to ``0.4``

**Comment by econotron** [comment]
OK, this is probably an issue of using the "nalimilan" packages for Fedora/RHEL etc, although these are specifically recommended on the Julia site at

http://julialang.org/downloads/platform.html
