### ISSUE TITLE
Applying ForwardDiff to functions that return literal constants results in a conversion error

### ISSUE THREAD

**Issue by mauro3** [JuliaDiff/ForwardDiff.jl#71]
This confused me for a while (well, in a more complex setting):
```
julia> derivative(x->0.0, 5.)
ERROR: MethodError: `convert` has no method matching convert(::Type{ForwardDiff.ForwardDiffResult{Float64}}, ::Float64)
This may have arisen from a call to the constructor ForwardDiff.ForwardDiffResult{Float64}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
  ForwardDiff.ForwardDiffResult{T}(::ForwardDiff.ForwardDiffNumber{N,T<:Number,C})
  ...
 in call at /home/mauro/.julia/v0.4/ForwardDiff/src/api/ForwardDiffResult.jl:11
 in derivative at /home/mauro/.julia/v0.4/ForwardDiff/src/api/derivative.jl:24
```

Could the error give a hint that `zero` needs to be used?

Also, the documentation says that the method needs to be type-stable, which `x->0.0` is.  Is the requirement that input and output type need to be equal?

**Comment by jrevels** [comment]
> Also, the documentation says that the method needs to be type-stable, which x->0.0 is. Is the requirement that input and output type need to be equal?

The documentation is correct, this is just an actual bug - there's no reason we shouldn't allow constant methods like your example here. 

I think it can be resolved fairly easily by loosening the restrictions on the way [`ForwardDiffResult`](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/api/ForwardDiffResult.jl#L5) is coded. I can get around to fixing it next week.

Thanks for finding this/reporting it!

**Comment by mauro3** [comment]
Thanks and no hurry, I'm ok with using `zero`.
