### ISSUE TITLE
A vector of second partial derivatives?

### ISSUE THREAD

**Issue by maximsch2** [JuliaDiff/ForwardDiff.jl#74]
Is there a quick way to compute a vector of second partial derivatives? Essentially, what I want is the diagonal of the Hessian, but since I only want a diagonal, computing the entire matrix is way too costly and it feels like there should be a better way.

**Comment by mlubin** [comment]
Definitely possible in theory, forward-mode AD is good for directional derivatives. I don't think there's an API for this though, related to https://github.com/JuliaDiff/ForwardDiff.jl/issues/43

**Comment by mlubin** [comment]
More specifically, to compute the diagonal of the hessian you'd need N function evaluations (in scalar forward mode), where N is the input dimension. To compute the full hessian you need O(N^2) evaluations, so there's a large gain if all you need is the diagonal.

**Comment by maximsch2** [comment]
As a motivating example, XGBoost requires both gradient and "hessian" (actually just the diagonal) to implement custom objective functions. Having the ability to efficiently evaluate both of them through combination with ForwardDiff would be a very attractive combo.

**Comment by mlubin** [comment]
Forward mode is not the most efficient way to get gradients, however. What's possibly more interesting is that if you are *given* an efficient gradient evaluation routine, you can very easy evaluate the diagonal of the hessian with a single forward-mode evaluation of the gradient routine.

**Comment by jrevels** [comment]
Let's move this to #43, which I've made the parent issue for specifying which partial derivatives are computed for sparse multidimensional differentiation operations.
