### ISSUE TITLE
Inference problem or ambiguous definition of `<`

### ISSUE THREAD

**Issue by pabloferz** [JuliaDiff/ForwardDiff.jl#76]
As mentioned <a href="https://groups.google.com/forum/#!topic/julia-users/e_ACdhwLHJg">here</a> using `isless(g::GradientNumber, x::Real)` works but `<(g::GradientNumber, x::Real)` doesn't.

I found that `<(g::GradientNumber, x::Real)` calls `<(x::Real, y::Real)` from julia's <a href="https://github.com/JuliaLang/julia/blob/master/base/promotion.jl">promotion.jl</a> instead of calling `isless(g::ForwardDiffNumber, x::Real)`. This promotes both arguments to `GradientNumber` and that reports there is no a corresponding method (although, I thought it was going to call the method `argument_error` <a href="https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/src/ForwardDiffNumber.jl#L78">from here</a>).

I'm not sure if this is a method ambiguity or an inference bug.

**Comment by jrevels** [comment]
Thanks for catching this! I just pushed a fix, let me know if this issue persists.

**Comment by pabloferz** [comment]
Thanks. It all works now!

**Comment by KristofferC** [comment]
Is it time to push a new version? Without this patch and #82  I have troubles with many of my functions. Of course I can use master but it seems that these two patches are quite important so a new version would be nice.

cc @jrevels

**Comment by mlubin** [comment]
@KristofferC you now have commit access, feel free to do the honors of tagging
