### ISSUE TITLE
Breaking change between v0.1.2 and v0.1.3

### ISSUE THREAD

**Issue by gragusa** [JuliaDiff/ForwardDiff.jl#78]
With the v0.1.2 I was able to do

```
x = randn(100)
function h(θ)
           m1 = θ[1] - x
           m2 = θ[2]^2 - (x - θ[1]).^2
           m3 = x.^3 - θ[1]*(θ[1]^2 + 3*θ[2]^2)
           return [m1 m2 m3]
       end

hh(theta) = vec(sum(h(theta), 1))

ForwardDiff.jacobian(hh, [.1, .1])
```

With the latest release (v.0.1.3) I get an error:

```
ERROR: InexactError()
 in setindex! at array.jl:313
 in .- at arraymath.jl:120
 in - at arraymath.jl:142
 in h at none:2
 in hh at none:1
 in _calc_jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:101
 in jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:27
```

I compared the release and does not seem to be any change that might have affected this. What am I missing?

**Comment by gragusa** [comment]
I have done some further investigations on the issue I am having and I think it has to do with broadcasting with `Array{Float64, 1}` and `Number`. 

For instance, with `ForwardDiff v0.1.3`, the following fail (as above)

x = randn(100)
function h(theta)
    theta[1] .- x        
end

hh(theta) = vec(sum(h(theta), 1))
ForwardDiff.jacobian(hh, [.1, .1])

```
x = randn(100)
function h(theta)
    theta[1] - x        
end

hh(theta) = vec(sum(h(theta), 1))
ForwardDiff.jacobian(hh, [.1, .1])
```
with 
```
ERROR: InexactError()
 in setindex! at array.jl:313
 in .- at arraymath.jl:120
 in - at arraymath.jl:142
 in hh at none:1
 in _calc_jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:101
 in jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:27
```

The following instead works:

```
x = randn(100)
function h(theta)
    [theta[1]] .- x        
end

hh(theta) = vec(sum(h(theta), 1))
ForwardDiff.jacobian(hh, [.1, .1])
```

**Comment by jrevels** [comment]
Interesting. I might not be able to look into this until next week, but I appreciate you bringing it up!

**Comment by gragusa** [comment]
You welcome. I will keep exploring. Could this be due to a type instability
in broadcasting or '-'?

**Comment by mlubin** [comment]
@gragusa, to debug this, I would trace ``@which theta[1] - x`` and see where it creates the incorrectly typed array.

**Comment by gragusa** [comment]
@mlubin Here some things I found 

```
print(theta)
2-element Array{ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}},1}:
 ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}(0.1,ForwardDiff.Partials{Float64,Tuple{Float64,Float64}}((1.0,0.0)))
 ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}(0.1,ForwardDiff.Partials{Float64,Tuple{Float64,Float64}}((0.0,1.0)))
```

```
@which theta[1.]-x
```

```
.-(x::Number, A::AbstractArray{T,N}) at arraymath.jl:118
```

The definition of `.-` is

```
function .-{T}(A::Number, B::AbstractArray{T})
      F = similar(B, promote_array_type($F,typeof(A),T))
      for i in eachindex(B)
          @inbounds F[i] = .-(A, B[i])
           end
           return F
       end
end
```

If I am not mistaken, the culprit is `promote_array_type` which is promoting F to be a Float64 instead of a `Array{ForwardDiff.GradientNumber}` (It seems that `promote_array_type` uses the logic that the `eltype` of the array dominates). I am not sure whether this is the reason, but for instance

```
theta[1]./x
```
works fine, because `./` is evaluated with list comprehension and so no confusion emerges on the eltype of the output.

**Comment by mlubin** [comment]
```julia
julia> Base.promote_array_type(Base.DotAddFun(), ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}, Float64)
Float64

julia> @which Base.promote_array_type(Base.DotAddFun(), ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}, Float64)
promote_array_type{S<:Real,A<:AbstractFloat}(F, ::Type{S<:Real}, ::Type{A<:AbstractFloat}) at arraymath.jl:42
```

**Comment by jrevels** [comment]
So I suppose we need to overload [that function](https://github.com/JuliaLang/julia/blob/8039d1bc34e26cd1f21e3ffb07fa8e544b031872/base/arraymath.jl#L42) for `ForwardDiffNumber`s then.

I'd be surprised if this hard-coded assumption on `Real` subtypes is an isolated case - there are probably other similarly tricky Base methods that we're going to need to overload for `ForwardDiffNumber`s now that they're subtyped to `Real`...
