### ISSUE TITLE
how can i run the benchmarks?

### ISSUE THREAD

**Issue by floswald** [JuliaDiff/ForwardDiff.jl#80]
hi there,

maybe i have got the wrong version (i did just `Pkg.add()`, and it's up to date), but I can't run the benchmarks. I was trying

```julia 
julia> include(joinpath(Pkg.dir("ForwardDiff"),"benchmarks","run_benchmarks.jl"))
Running Julia benchmarks...
INFO: Recompiling stale cache file /Users/florian.oswald/.julia/lib/v0.4/JLD.ji for module JLD.
INFO: Recompiling stale cache file /Users/florian.oswald/.julia/lib/v0.4/HDF5.ji for module HDF5.
INFO: Recompiling stale cache file /Users/florian.oswald/.julia/lib/v0.4/Blosc.ji for module Blosc.
ERROR: LoadError: LoadError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named benchmarks',)

 [inlined code] from /Users/florian.oswald/.julia/v0.4/PyCall/src/exception.jl:81
 in pyimport at /Users/florian.oswald/.julia/v0.4/PyCall/src/PyCall.jl:79
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/florian.oswald/.julia/v0.4/ForwardDiff/benchmarks/benchmarks.jl, in expression starting on line 341
while loading /Users/florian.oswald/.julia/v0.4/ForwardDiff/benchmarks/run_benchmarks.jl, in expression starting on line 2
```

**Comment by jrevels** [comment]
Hi! I'm not sure what version of ForwardDiff you're using, but the file you're trying to `include` doesn't exist in the current version. [These files](https://github.com/JuliaDiff/ForwardDiff.jl/blob/master/benchmarks) contain utilities for running the benchmarks discussed in [this blog post](http://julialang.org/blog/2015/10/auto-diff-in-julia/).

**Comment by mlubin** [comment]
Make sure you're on Julia 0.4.0 release or greater.

**Comment by floswald** [comment]
Hi guys
I'm definitely on Julia 0.4. I have seen that my files don't correspond to
GitHub. As I said, this persists after pkg.update(), Which in fact did not
update forwarddiff.
I'm sure I did not pin it somewhere either. So I'm a bit puzzled :-)
I'll try removing and reinstalling it tomorrow.

**Comment by KristofferC** [comment]
The package could be dirty (you got uncomitted stuff in it). What happens if you run Pkg.status()

**Comment by jrevels** [comment]
I'm going to close this now, but feel free to comment here if you need further assistance.
