### ISSUE TITLE
Bug related to data() function

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ForwardDiff.jl#87]
When I use Lora with Julia v0.4.2 for a (Lora) script, it runs fine. However, when I try the same script with Julia v0.5, it fails yielding the following error:

```
ERROR: MethodError: `start` has no method matching start(::Function)
 in ##run_basicmcjob#10667 at /Users/theodore/.julia/v0.5/Lora/src/jobs/BasicMCJob.jl:329
 in run at /Users/theodore/.julia/v0.5/Lora/src/jobs/BasicMCJob.jl:382
 in eval at /Applications/Julia-0.5.0-dev-31b04bde2d.app/Contents/Resources/julia/lib/julia/sys.dylib
```

I am quite certain this is a bug in ForwardDiff; Lora does not define a `data()` function, so this must relate to the import of ForwardDiff from Lora (since ForwardDiff defines `data()`).

**Comment by scidom** [comment]
P.S. The error above is related to the `start()` function in ForwardDiff, which is due to running the most recent nightly of Julia 0.5. Before this attempt, I had tried an older version of 0.5 (33 days old commit, which gave the `data()`-related error, which is also a function in ForwardDiff). All in all, ForwardDiff seems to behave a bit erratically with the dev version of Julia...

**Comment by mlubin** [comment]
Do you have an example of an error that doesn't involve code dynamically generated by Lora? There could easily be a scoping issue in your code generation logic.

**Comment by scidom** [comment]
Thanks @mlubin. It is hard to think how to create a standalone example, simply because I have no clue where the error could be coming from. Do you mean there may be a scoping issue related to Lora? Yes, this is possible, what puzzles me is that there hasn't been such issue so far with Julia 0.4.1 and 0.4.2... if there is a scoping problem i have no idea how to work on this to detect it and fix it...

**Comment by mlubin** [comment]
Well, generate the code and paste it into a file. Then run the function from that file.

**Comment by scidom** [comment]
I see what you mean now. Yes, this is how I developed and tested the code in the first instance. Printing the code-generated function via `Lora.codegen_run_basicmcjob(job)` gives

```
julia> Lora.codegen_run_basicmcjob(job)
quote  # /Users/theodore/.julia/v0.5/Lora/src/jobs/BasicMCJob.jl, line 328:
    function ##run_basicmcjob#11158() # /Users/theodore/.julia/v0.5/Lora/src/jobs/BasicMCJob.jl, line 329:
        for i in 1:job.range.nsteps
            job.iterate!(job.pstate,job.sstate,job.parameter,job.sampler,job.tuner,job.range)
            if i in job.range.postrange
                job.count += 1
                job.save!(job.count)
            end
        end
        return job.output
    end
end
```

Evaluating this function throws the error I had mentioned initially, plus the `job` that appears in the quoted expression is the result of "pretty-printing" a reference to a job that is hooked in the definition of the code-generated `run_basicmcjob` (it is not passed as an arg at runtime). I still don't undrestand why this error appears in julia 0.5 and not in the stable version 0.4.2 - even if it is a scoping issue, where exactly did it arise down the road?

If you are entirely convinced this is a Lora error completely irrelevant to ForwardDiff, feel free to close the issue. It feels disappointing after several months of development to see Lora broken in a way that I can not comprehend or fix so as to move on, but will try to get back to it at some point in the future with a fresher mind.

**Comment by mlubin** [comment]
Where does ``ForwardDiff`` come in here? What parameters are you using ``ForwardDiff`` to differentiate with respect to? Does the same error occur if you evaluate the function normally (i.e., not using ``ForwardDiff``)?

**Comment by scidom** [comment]
This is what puzzles me, as `ForwardDiff` should not be really implicated. Evaluating the above code-generated function yields

```
julia> myf = eval(Lora.codegen_run_basicmcjob(job))
##run_basicmcjob#11160 (generic function with 1 method)

julia> myf()
ERROR: MethodError: `data` has no method matching data(::Function)
 in ##run_basicmcjob#11160 at /Users/theodore/.julia/v0.5/Lora/src/jobs/BasicMCJob.jl:329
 in eval at /Applications/Julia-0.5.0-dev-31b04bde2d.app/Contents/Resources/julia/lib/julia/sys.dylib
```

There is no `data()` function in Lora, but there is in ForwardDiff , as it can be seen by running `grep -R "data" ~/.julia/v0.5/ForwardDiff`. One of the constructors of `BasicContMuvParameter` uses ForwardDiff, but the odd thing is that I do not use that specific constructor, so the above error should not appear...

**Comment by scidom** [comment]
P.S. `job.parameter` could be implicitly related to ForwardDiff, but the way `job.parameter` has been constructed should not relate to ForwardDiff in this example.

**Comment by scidom** [comment]
Furthermore, I checked that `job.parameter.gradlogtarget!` in this example is set to `nothing`, which confirms my suspision that ForwardDiff has not been called indeed, as it shouldn't.

**Comment by mlubin** [comment]
Not sure how much more I can help without a self-contained (<50 lines) reproducible example. If ``ForwardDiff`` isn't being called here, it's hard to see how it could be the cause. ``data`` is defined in ``ForwardDiff``, but it's not exported.

**Comment by scidom** [comment]
I understand this, you are right. I will provide a 30-40 lines example but it would be calling Lora. I will try to think the next few days if I can possibly create an example disentangled from Lora and will let you know.

**Comment by scidom** [comment]
I think I may get to the bottom of this. After a bit of manual debugging, it seems that the following expression related to control flow is parsed differently in Julia 0.4.2 and 0.5:

```
Expr(:for, :(i in 1:5), Expr(:block, [:(x = x+i)]...))
```

In 0.4.2 it gives

```
julia> Expr(:for, :(i in 1:5), Expr(:block, [:(x = x+i)]...))
:(for $(Expr(:in, :i, :(1:5)))
        x = x + i
    end)
```

while in 0.5 it gives

```
julia> Expr(:for, :(i in 1:5), Expr(:block, [:(x = x+i)]...))
:(for i in 1:5
        x = x + i
    end)
```

I may be able to fix this now...

**Comment by scidom** [comment]
Yes, I fixed it... I changed

```
Expr(:for, :(i in 1:5), Expr(:block, [:(x = x+i)]...))
```

to 

```
Expr(:for, :(i = 1:5), Expr(:block, [:(x = x+i)]...))
```

to avoid the parsing of `in` expressions, that are represented differently in Julia 0.5 as expressions with head `:comparison`.
