### ISSUE TITLE
GradientNumber Promotion Error on Julia v0.5

### ISSUE THREAD

**Issue by scidom** [JuliaDiff/ForwardDiff.jl#88]
The following example fails:

```
import ForwardDiff

f(x::Vector) = exp(x)
g = ForwardDiff.gradient(f)

g([3.5, 4.1])
```

The error I get is the following:

```
julia> g([3.5, 4.1])
ERROR: MethodError: `convert` has no method matching convert(::Type{ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}}, ::Array{ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}},1})
This may have arisen from a call to the constructor ForwardDiff.GradientNumber{2,Float64,Tuple{Float64,Float64}}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  ForwardDiff.GradientNumber{N,T,C}(::Any, ::Any)
  call{T}(::Type{T}, ::Any)
  convert{T<:Real}(::Type{T<:Real}, ::Complex{T<:Real})
  ...
 in _calc_gradient at /Users/theodore/.julia/v0.4/ForwardDiff/src/api/gradient.jl:86
 in g at /Users/theodore/.julia/v0.4/ForwardDiff/src/api/gradient.jl:54
```

**Comment by KristofferC** [comment]
'f'  need to return a scalar, no?

**Comment by jrevels** [comment]
`f` here is a function from a `Vector` to a `Vector`, you need to use `ForwardDiff.jacobian` instead of `ForwardDiff.gradient`.

We should probably have a better error message for this, since it seems to be a common mistake.

**Comment by scidom** [comment]
Sorry about this @jrevels, @KristofferC , you are right, I should had used the `jacobian`. The thing is that I actually need the gradient, but in a different context/example. I tried to somehow construct a simpler example focusing on the initial error message I was getting, and I obviously failed...!

I will try to come up with a better example related to what I am trying to do and what error message I get.

**Comment by scidom** [comment]
Ok, attempt 2 to construct a relevant example. This is similar to what I am trying to do:

```
import ForwardDiff

f(x::Vector) = sum(1+exp(x))
g = ForwardDiff.gradient(f)

g([3.5, 4.1])
```

This is the error I get:

```
julia> g([3.5, 4.1])
ERROR: no promotion exists for Int64 and ForwardDiff.GradientNumber{N,T,C}
 [inlined code] from promotion.jl:160
 in .+ at arraymath.jl:119
 [inlined code] from arraymath.jl:141
 in f at none:1
 in _calc_gradient at /Users/theodore/.julia/v0.5/ForwardDiff/src/api/gradient.jl:86
 in g at /Users/theodore/.julia/v0.5/ForwardDiff/src/api/gradient.jl:54
 in eval at /Applications/Julia-0.5.0-dev-e55c22a793.app/Contents/Resources/julia/lib/julia/sys.dylib
```

**Comment by jrevels** [comment]
Hmm. Looks like v0.5-specific breakage. It seems to work on v0.4:

```julia
julia> import ForwardDiff

julia> f(x::Vector) = sum(1+exp(x))
f (generic function with 1 method)

julia> g = ForwardDiff.gradient(f)
g (generic function with 1 method)

julia> g([3.5, 4.1])
2-element Array{Float64,1}:
 33.1155
 60.3403
```

**Comment by scidom** [comment]
Ah, yes, it works on v0.4, didn't notice :)

**Comment by KristofferC** [comment]
I don't think the problem is with the promotion but in type inference, maybe same as #75.

**Comment by jrevels** [comment]
This now works, either due to advances in Julia v0.5 or #102.
