### ISSUE TITLE
Sparse Jacobian

### ISSUE THREAD

**Issue by matthieugomez** [JuliaDiff/ForwardDiff.jl#91]
First this is a great package!

Is there be a simple way to make ForwardDiff faster for sparse problems, i.e. problems where the user already knows the value of most of the elements of the Jacobian, and this value is zero. This happens when solving Finite Difference Schemes.

A simple example is the following:
```julia
using ForwardDiff
function f(x::Vector)
	out = deepcopy(x)
	for i in 2:length(x)
		out[i] = x[i - 1] 
	end
	return out
end
for i in 2:6
	n = Int(5^i)
	x = rand(n)
	J =  rand(n, n)
	@time jacobian!(J, f, x)
end
```
Could this be faster if the user could provide the sparsity structure of the Jacobian?

**Comment by mlubin** [comment]
> Could this be faster if the user could provide the sparsity structure of the Jacobian?

Definitely. You need to combine https://github.com/JuliaDiff/ForwardDiff.jl/issues/43 with https://github.com/mauro3/MatrixColorings.jl.

**Comment by jrevels** [comment]
Let's move this to #43, which I've made the parent issue for specifying which partial derivatives are computed for sparse multidimensional differentiation operations.

**Comment by mauro3** [comment]
Sparse Jacobians would be very useful for ODE/DAE solving.  ForwardDiff + https://github.com/mauro3/MatrixColorings.jl gets us most of the way there but the latter is in need of some love.

I'm not sure whether #43 is really the same issue as this one, so maybe worth keeping this open?
